// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/chat/conversations.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/chat/conversations
pub async fn get(
    http: &Http,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = "chat/conversations";
    http.send_with_query(Method::GET, path, req).await
}

