// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/lists/{id}.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/lists/{id}
pub async fn get(
    http: &Http,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = format!("lists/{}", urlencoding::encode(&req.id.to_string()));
    http.send_with_query(Method::GET, &path, req).await
}

/// PUT /2/lists/{id}
pub async fn put(
    http: &Http,
    req: &super::put::Request,
) -> Result<super::put::Response, Error> {
    let path = format!("lists/{}", urlencoding::encode(&req.id.to_string()));
    http.send(Method::PUT, &path, req.body.as_ref()).await
}

/// DELETE /2/lists/{id}
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("lists/{}", urlencoding::encode(&req.id.to_string()));
    http.send::<_, ()>(Method::DELETE, &path, None).await
}

