// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/communities/{id} — Get Community by ID
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub id: CommunityId,
    #[serde(rename = "community.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub community_fields: Option<Vec<crate::x::params::community_fields_parameter::CommunityFields>>,
}

pub type Response = Get2CommunitiesIdResponse;

