// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/tweets/{id}/quote_tweets — Get Quoted Posts
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub id: TweetId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pagination_token: Option<PaginationToken36>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude: Option<Vec<RequestExcludeItem>>,
    #[serde(rename = "tweet.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub tweet_fields: Option<Vec<crate::x::params::tweet_fields_parameter::TweetFields>>,
    #[serde(rename = "expansions", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub expansions: Option<Vec<crate::x::params::tweet_expansions_parameter::TweetExpansions>>,
    #[serde(rename = "media.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub media_fields: Option<Vec<crate::x::params::media_fields_parameter::MediaFields>>,
    #[serde(rename = "poll.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub poll_fields: Option<Vec<crate::x::params::poll_fields_parameter::PollFields>>,
    #[serde(rename = "user.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub user_fields: Option<Vec<crate::x::params::user_fields_parameter::UserFields>>,
    #[serde(rename = "place.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub place_fields: Option<Vec<crate::x::params::place_fields_parameter::PlaceFields>>,
}

pub type Response = Get2TweetsIdQuoteTweetsResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestExcludeItem {
    #[serde(rename = "replies")]
    Replies,
    #[serde(rename = "retweets")]
    Retweets,
}

