// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! DELETE /2/users/{id}/retweets/{source_tweet_id} — Unrepost Post
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub id: UserIdMatchesAuthenticatedUser,
    pub source_tweet_id: TweetId,
}

pub type Response = UsersRetweetsDeleteResponse;

