// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/media/upload — Get Media upload status
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    pub media_id: MediaId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<RequestCommand>,
}

pub type Response = MediaUploadResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestCommand {
    #[serde(rename = "STATUS")]
    STATUS,
}

impl std::fmt::Display for RequestCommand {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestCommand::STATUS => "STATUS",
        })
    }
}

