// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AnalyticsFields {
    #[serde(rename = "app_install_attempts")]
    AppInstallAttempts,
    #[serde(rename = "app_opens")]
    AppOpens,
    #[serde(rename = "bookmarks")]
    Bookmarks,
    #[serde(rename = "detail_expands")]
    DetailExpands,
    #[serde(rename = "email_tweet")]
    EmailTweet,
    #[serde(rename = "engagements")]
    Engagements,
    #[serde(rename = "follows")]
    Follows,
    #[serde(rename = "hashtag_clicks")]
    HashtagClicks,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "impressions")]
    Impressions,
    #[serde(rename = "likes")]
    Likes,
    #[serde(rename = "media_views")]
    MediaViews,
    #[serde(rename = "permalink_clicks")]
    PermalinkClicks,
    #[serde(rename = "quote_tweets")]
    QuoteTweets,
    #[serde(rename = "replies")]
    Replies,
    #[serde(rename = "retweets")]
    Retweets,
    #[serde(rename = "shares")]
    Shares,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "unfollows")]
    Unfollows,
    #[serde(rename = "unlikes")]
    Unlikes,
    #[serde(rename = "url_clicks")]
    UrlClicks,
    #[serde(rename = "user_profile_clicks")]
    UserProfileClicks,
}

impl std::fmt::Display for AnalyticsFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            AnalyticsFields::AppInstallAttempts => "app_install_attempts",
            AnalyticsFields::AppOpens => "app_opens",
            AnalyticsFields::Bookmarks => "bookmarks",
            AnalyticsFields::DetailExpands => "detail_expands",
            AnalyticsFields::EmailTweet => "email_tweet",
            AnalyticsFields::Engagements => "engagements",
            AnalyticsFields::Follows => "follows",
            AnalyticsFields::HashtagClicks => "hashtag_clicks",
            AnalyticsFields::Id => "id",
            AnalyticsFields::Impressions => "impressions",
            AnalyticsFields::Likes => "likes",
            AnalyticsFields::MediaViews => "media_views",
            AnalyticsFields::PermalinkClicks => "permalink_clicks",
            AnalyticsFields::QuoteTweets => "quote_tweets",
            AnalyticsFields::Replies => "replies",
            AnalyticsFields::Retweets => "retweets",
            AnalyticsFields::Shares => "shares",
            AnalyticsFields::Timestamp => "timestamp",
            AnalyticsFields::Unfollows => "unfollows",
            AnalyticsFields::Unlikes => "unlikes",
            AnalyticsFields::UrlClicks => "url_clicks",
            AnalyticsFields::UserProfileClicks => "user_profile_clicks",
        })
    }
}

