// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChatConversationExpansions {
    #[serde(rename = "admin_ids")]
    AdminIds,
    #[serde(rename = "member_ids")]
    MemberIds,
    #[serde(rename = "participant_ids")]
    ParticipantIds,
}

impl std::fmt::Display for ChatConversationExpansions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ChatConversationExpansions::AdminIds => "admin_ids",
            ChatConversationExpansions::MemberIds => "member_ids",
            ChatConversationExpansions::ParticipantIds => "participant_ids",
        })
    }
}

