// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChatMessageEventFields {
    #[serde(rename = "conversation_id")]
    ConversationId,
    #[serde(rename = "conversation_token")]
    ConversationToken,
    #[serde(rename = "created_at_msec")]
    CreatedAtMsec,
    #[serde(rename = "encoded_event")]
    EncodedEvent,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "is_trusted")]
    IsTrusted,
    #[serde(rename = "message_event_signature")]
    MessageEventSignature,
    #[serde(rename = "previous_id")]
    PreviousId,
    #[serde(rename = "sender_id")]
    SenderId,
}

impl std::fmt::Display for ChatMessageEventFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ChatMessageEventFields::ConversationId => "conversation_id",
            ChatMessageEventFields::ConversationToken => "conversation_token",
            ChatMessageEventFields::CreatedAtMsec => "created_at_msec",
            ChatMessageEventFields::EncodedEvent => "encoded_event",
            ChatMessageEventFields::Id => "id",
            ChatMessageEventFields::IsTrusted => "is_trusted",
            ChatMessageEventFields::MessageEventSignature => "message_event_signature",
            ChatMessageEventFields::PreviousId => "previous_id",
            ChatMessageEventFields::SenderId => "sender_id",
        })
    }
}

