// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CommunityFields {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "join_policy")]
    JoinPolicy,
    #[serde(rename = "member_count")]
    MemberCount,
    #[serde(rename = "name")]
    Name,
}

impl std::fmt::Display for CommunityFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            CommunityFields::Access => "access",
            CommunityFields::CreatedAt => "created_at",
            CommunityFields::Description => "description",
            CommunityFields::Id => "id",
            CommunityFields::JoinPolicy => "join_policy",
            CommunityFields::MemberCount => "member_count",
            CommunityFields::Name => "name",
        })
    }
}

