// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ComplianceJobFields {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "download_expires_at")]
    DownloadExpiresAt,
    #[serde(rename = "download_url")]
    DownloadUrl,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "resumable")]
    Resumable,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "upload_expires_at")]
    UploadExpiresAt,
    #[serde(rename = "upload_url")]
    UploadUrl,
}

impl std::fmt::Display for ComplianceJobFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ComplianceJobFields::CreatedAt => "created_at",
            ComplianceJobFields::DownloadExpiresAt => "download_expires_at",
            ComplianceJobFields::DownloadUrl => "download_url",
            ComplianceJobFields::Id => "id",
            ComplianceJobFields::Name => "name",
            ComplianceJobFields::Resumable => "resumable",
            ComplianceJobFields::Status => "status",
            ComplianceJobFields::Type => "type",
            ComplianceJobFields::UploadExpiresAt => "upload_expires_at",
            ComplianceJobFields::UploadUrl => "upload_url",
        })
    }
}

