// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ConnectionFields {
    #[serde(rename = "client_ip")]
    ClientIp,
    #[serde(rename = "connected_at")]
    ConnectedAt,
    #[serde(rename = "disconnect_reason")]
    DisconnectReason,
    #[serde(rename = "disconnected_at")]
    DisconnectedAt,
    #[serde(rename = "endpoint_name")]
    EndpointName,
    #[serde(rename = "id")]
    Id,
}

