// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ConnectionFields {
    #[serde(rename = "client_ip")]
    ClientIp,
    #[serde(rename = "connected_at")]
    ConnectedAt,
    #[serde(rename = "disconnect_reason")]
    DisconnectReason,
    #[serde(rename = "disconnected_at")]
    DisconnectedAt,
    #[serde(rename = "endpoint_name")]
    EndpointName,
    #[serde(rename = "id")]
    Id,
}

impl std::fmt::Display for ConnectionFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ConnectionFields::ClientIp => "client_ip",
            ConnectionFields::ConnectedAt => "connected_at",
            ConnectionFields::DisconnectReason => "disconnect_reason",
            ConnectionFields::DisconnectedAt => "disconnected_at",
            ConnectionFields::EndpointName => "endpoint_name",
            ConnectionFields::Id => "id",
        })
    }
}

