// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DmEventExpansions {
    #[serde(rename = "attachments.media_keys")]
    AttachmentsMediaKeys,
    #[serde(rename = "participant_ids")]
    ParticipantIds,
    #[serde(rename = "referenced_tweets.id")]
    ReferencedTweetsId,
    #[serde(rename = "sender_id")]
    SenderId,
}

impl std::fmt::Display for DmEventExpansions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            DmEventExpansions::AttachmentsMediaKeys => "attachments.media_keys",
            DmEventExpansions::ParticipantIds => "participant_ids",
            DmEventExpansions::ReferencedTweetsId => "referenced_tweets.id",
            DmEventExpansions::SenderId => "sender_id",
        })
    }
}

