// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DmEventFields {
    #[serde(rename = "attachments")]
    Attachments,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "dm_conversation_id")]
    DmConversationId,
    #[serde(rename = "entities")]
    Entities,
    #[serde(rename = "event_type")]
    EventType,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "participant_ids")]
    ParticipantIds,
    #[serde(rename = "referenced_tweets")]
    ReferencedTweets,
    #[serde(rename = "sender_id")]
    SenderId,
    #[serde(rename = "text")]
    Text,
}

impl std::fmt::Display for DmEventFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            DmEventFields::Attachments => "attachments",
            DmEventFields::CreatedAt => "created_at",
            DmEventFields::DmConversationId => "dm_conversation_id",
            DmEventFields::Entities => "entities",
            DmEventFields::EventType => "event_type",
            DmEventFields::Id => "id",
            DmEventFields::ParticipantIds => "participant_ids",
            DmEventFields::ReferencedTweets => "referenced_tweets",
            DmEventFields::SenderId => "sender_id",
            DmEventFields::Text => "text",
        })
    }
}

