// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DmEventFields {
    #[serde(rename = "attachments")]
    Attachments,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "dm_conversation_id")]
    DmConversationId,
    #[serde(rename = "entities")]
    Entities,
    #[serde(rename = "event_type")]
    EventType,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "participant_ids")]
    ParticipantIds,
    #[serde(rename = "referenced_tweets")]
    ReferencedTweets,
    #[serde(rename = "sender_id")]
    SenderId,
    #[serde(rename = "text")]
    Text,
}

