// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EngagementFields {
    #[serde(rename = "errors")]
    Errors,
    #[serde(rename = "measurement")]
    Measurement,
}

impl std::fmt::Display for EngagementFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            EngagementFields::Errors => "errors",
            EngagementFields::Measurement => "measurement",
        })
    }
}

