// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LikeFields {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "liked_tweet_id")]
    LikedTweetId,
    #[serde(rename = "timestamp_ms")]
    TimestampMs,
}

