// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LikeFields {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "liked_tweet_id")]
    LikedTweetId,
    #[serde(rename = "timestamp_ms")]
    TimestampMs,
}

impl std::fmt::Display for LikeFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            LikeFields::CreatedAt => "created_at",
            LikeFields::Id => "id",
            LikeFields::LikedTweetId => "liked_tweet_id",
            LikeFields::TimestampMs => "timestamp_ms",
        })
    }
}

