// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LikeWithTweetAuthorFields {
    #[serde(rename = "attachments_media_keys")]
    AttachmentsMediaKeys,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "liked_tweet_author_id")]
    LikedTweetAuthorId,
    #[serde(rename = "liked_tweet_id")]
    LikedTweetId,
    #[serde(rename = "timestamp_ms")]
    TimestampMs,
}

impl std::fmt::Display for LikeWithTweetAuthorFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            LikeWithTweetAuthorFields::AttachmentsMediaKeys => "attachments_media_keys",
            LikeWithTweetAuthorFields::CreatedAt => "created_at",
            LikeWithTweetAuthorFields::Id => "id",
            LikeWithTweetAuthorFields::LikedTweetAuthorId => "liked_tweet_author_id",
            LikeWithTweetAuthorFields::LikedTweetId => "liked_tweet_id",
            LikeWithTweetAuthorFields::TimestampMs => "timestamp_ms",
        })
    }
}

