// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LikeWithTweetAuthorExpansions {
    #[serde(rename = "attachments.media_keys")]
    AttachmentsMediaKeys,
    #[serde(rename = "liked_tweet_author_id")]
    LikedTweetAuthorId,
    #[serde(rename = "liked_tweet_id")]
    LikedTweetId,
}

impl std::fmt::Display for LikeWithTweetAuthorExpansions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            LikeWithTweetAuthorExpansions::AttachmentsMediaKeys => "attachments.media_keys",
            LikeWithTweetAuthorExpansions::LikedTweetAuthorId => "liked_tweet_author_id",
            LikeWithTweetAuthorExpansions::LikedTweetId => "liked_tweet_id",
        })
    }
}

