// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MarketplaceHandleAvailabilityFields {
    #[serde(rename = "availability_state")]
    AvailabilityState,
    #[serde(rename = "redirect_url")]
    RedirectUrl,
}

