// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaAnalyticsFields {
    #[serde(rename = "cta_url_clicks")]
    CtaUrlClicks,
    #[serde(rename = "cta_watch_clicks")]
    CtaWatchClicks,
    #[serde(rename = "media_key")]
    MediaKey,
    #[serde(rename = "play_from_tap")]
    PlayFromTap,
    #[serde(rename = "playback25")]
    Playback25,
    #[serde(rename = "playback50")]
    Playback50,
    #[serde(rename = "playback75")]
    Playback75,
    #[serde(rename = "playback_complete")]
    PlaybackComplete,
    #[serde(rename = "playback_start")]
    PlaybackStart,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "video_views")]
    VideoViews,
    #[serde(rename = "watch_time_ms")]
    WatchTimeMs,
}

