// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaAnalyticsFields {
    #[serde(rename = "cta_url_clicks")]
    CtaUrlClicks,
    #[serde(rename = "cta_watch_clicks")]
    CtaWatchClicks,
    #[serde(rename = "media_key")]
    MediaKey,
    #[serde(rename = "play_from_tap")]
    PlayFromTap,
    #[serde(rename = "playback25")]
    Playback25,
    #[serde(rename = "playback50")]
    Playback50,
    #[serde(rename = "playback75")]
    Playback75,
    #[serde(rename = "playback_complete")]
    PlaybackComplete,
    #[serde(rename = "playback_start")]
    PlaybackStart,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "video_views")]
    VideoViews,
    #[serde(rename = "watch_time_ms")]
    WatchTimeMs,
}

impl std::fmt::Display for MediaAnalyticsFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            MediaAnalyticsFields::CtaUrlClicks => "cta_url_clicks",
            MediaAnalyticsFields::CtaWatchClicks => "cta_watch_clicks",
            MediaAnalyticsFields::MediaKey => "media_key",
            MediaAnalyticsFields::PlayFromTap => "play_from_tap",
            MediaAnalyticsFields::Playback25 => "playback25",
            MediaAnalyticsFields::Playback50 => "playback50",
            MediaAnalyticsFields::Playback75 => "playback75",
            MediaAnalyticsFields::PlaybackComplete => "playback_complete",
            MediaAnalyticsFields::PlaybackStart => "playback_start",
            MediaAnalyticsFields::Timestamp => "timestamp",
            MediaAnalyticsFields::VideoViews => "video_views",
            MediaAnalyticsFields::WatchTimeMs => "watch_time_ms",
        })
    }
}

