// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaFields {
    #[serde(rename = "alt_text")]
    AltText,
    #[serde(rename = "duration_ms")]
    DurationMs,
    #[serde(rename = "height")]
    Height,
    #[serde(rename = "media_key")]
    MediaKey,
    #[serde(rename = "non_public_metrics")]
    NonPublicMetrics,
    #[serde(rename = "organic_metrics")]
    OrganicMetrics,
    #[serde(rename = "preview_image_url")]
    PreviewImageUrl,
    #[serde(rename = "promoted_metrics")]
    PromotedMetrics,
    #[serde(rename = "public_metrics")]
    PublicMetrics,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "variants")]
    Variants,
    #[serde(rename = "width")]
    Width,
}

