// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NewsFields {
    #[serde(rename = "category")]
    Category,
    #[serde(rename = "cluster_posts_results")]
    ClusterPostsResults,
    #[serde(rename = "contexts")]
    Contexts,
    #[serde(rename = "disclaimer")]
    Disclaimer,
    #[serde(rename = "hook")]
    Hook,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "keywords")]
    Keywords,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "summary")]
    Summary,
    #[serde(rename = "updated_at")]
    UpdatedAt,
}

