// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NoteFields {
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "scoring_status")]
    ScoringStatus,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "test_result")]
    TestResult,
}

impl std::fmt::Display for NoteFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            NoteFields::Id => "id",
            NoteFields::Info => "info",
            NoteFields::ScoringStatus => "scoring_status",
            NoteFields::Status => "status",
            NoteFields::TestResult => "test_result",
        })
    }
}

