// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PersonalizedTrendFields {
    #[serde(rename = "category")]
    Category,
    #[serde(rename = "post_count")]
    PostCount,
    #[serde(rename = "trend_name")]
    TrendName,
    #[serde(rename = "trending_since")]
    TrendingSince,
}

impl std::fmt::Display for PersonalizedTrendFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PersonalizedTrendFields::Category => "category",
            PersonalizedTrendFields::PostCount => "post_count",
            PersonalizedTrendFields::TrendName => "trend_name",
            PersonalizedTrendFields::TrendingSince => "trending_since",
        })
    }
}

