// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaceFields {
    #[serde(rename = "contained_within")]
    ContainedWithin,
    #[serde(rename = "country")]
    Country,
    #[serde(rename = "country_code")]
    CountryCode,
    #[serde(rename = "full_name")]
    FullName,
    #[serde(rename = "geo")]
    Geo,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "place_type")]
    PlaceType,
}

impl std::fmt::Display for PlaceFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PlaceFields::ContainedWithin => "contained_within",
            PlaceFields::Country => "country",
            PlaceFields::CountryCode => "country_code",
            PlaceFields::FullName => "full_name",
            PlaceFields::Geo => "geo",
            PlaceFields::Id => "id",
            PlaceFields::Name => "name",
            PlaceFields::PlaceType => "place_type",
        })
    }
}

