// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaidAccountTransactionFields {
    #[serde(rename = "accountCategory")]
    AccountCategory,
    #[serde(rename = "amount")]
    Amount,
    #[serde(rename = "debitCreditMemo")]
    DebitCreditMemo,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "postedTimestamp")]
    PostedTimestamp,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "transactionId")]
    TransactionId,
    #[serde(rename = "transactionTimestamp")]
    TransactionTimestamp,
}

