// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaidAccountFields {
    #[serde(rename = "accountCategory")]
    AccountCategory,
    #[serde(rename = "accountId")]
    AccountId,
    #[serde(rename = "accountNumberDisplay")]
    AccountNumberDisplay,
    #[serde(rename = "accountType")]
    AccountType,
    #[serde(rename = "availableBalance")]
    AvailableBalance,
    #[serde(rename = "currency")]
    Currency,
    #[serde(rename = "currentBalance")]
    CurrentBalance,
    #[serde(rename = "nickname")]
    Nickname,
    #[serde(rename = "productName")]
    ProductName,
    #[serde(rename = "status")]
    Status,
}

impl std::fmt::Display for PlaidAccountFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PlaidAccountFields::AccountCategory => "accountCategory",
            PlaidAccountFields::AccountId => "accountId",
            PlaidAccountFields::AccountNumberDisplay => "accountNumberDisplay",
            PlaidAccountFields::AccountType => "accountType",
            PlaidAccountFields::AvailableBalance => "availableBalance",
            PlaidAccountFields::Currency => "currency",
            PlaidAccountFields::CurrentBalance => "currentBalance",
            PlaidAccountFields::Nickname => "nickname",
            PlaidAccountFields::ProductName => "productName",
            PlaidAccountFields::Status => "status",
        })
    }
}

