// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaidAccountContactFields {
    #[serde(rename = "addresses")]
    Addresses,
    #[serde(rename = "emails")]
    Emails,
    #[serde(rename = "holders")]
    Holders,
    #[serde(rename = "telephones")]
    Telephones,
}

impl std::fmt::Display for PlaidAccountContactFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PlaidAccountContactFields::Addresses => "addresses",
            PlaidAccountContactFields::Emails => "emails",
            PlaidAccountContactFields::Holders => "holders",
            PlaidAccountContactFields::Telephones => "telephones",
        })
    }
}

