// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaidAccountFields {
    #[serde(rename = "accountCategory")]
    AccountCategory,
    #[serde(rename = "accountId")]
    AccountId,
    #[serde(rename = "accountNumberDisplay")]
    AccountNumberDisplay,
    #[serde(rename = "accountType")]
    AccountType,
    #[serde(rename = "availableBalance")]
    AvailableBalance,
    #[serde(rename = "currency")]
    Currency,
    #[serde(rename = "currentBalance")]
    CurrentBalance,
    #[serde(rename = "nickname")]
    Nickname,
    #[serde(rename = "productName")]
    ProductName,
    #[serde(rename = "status")]
    Status,
}

