// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaidAccountTransactionFields {
    #[serde(rename = "accountCategory")]
    AccountCategory,
    #[serde(rename = "amount")]
    Amount,
    #[serde(rename = "debitCreditMemo")]
    DebitCreditMemo,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "postedTimestamp")]
    PostedTimestamp,
    #[serde(rename = "status")]
    Status,
    #[serde(rename = "transactionId")]
    TransactionId,
    #[serde(rename = "transactionTimestamp")]
    TransactionTimestamp,
}

impl std::fmt::Display for PlaidAccountTransactionFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PlaidAccountTransactionFields::AccountCategory => "accountCategory",
            PlaidAccountTransactionFields::Amount => "amount",
            PlaidAccountTransactionFields::DebitCreditMemo => "debitCreditMemo",
            PlaidAccountTransactionFields::Description => "description",
            PlaidAccountTransactionFields::PostedTimestamp => "postedTimestamp",
            PlaidAccountTransactionFields::Status => "status",
            PlaidAccountTransactionFields::TransactionId => "transactionId",
            PlaidAccountTransactionFields::TransactionTimestamp => "transactionTimestamp",
        })
    }
}

