// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PollFields {
    #[serde(rename = "duration_minutes")]
    DurationMinutes,
    #[serde(rename = "end_datetime")]
    EndDatetime,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "options")]
    Options,
    #[serde(rename = "voting_status")]
    VotingStatus,
}

