// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PublicKeyFields {
    #[serde(rename = "juicebox_config")]
    JuiceboxConfig,
    #[serde(rename = "public_key")]
    PublicKey,
    #[serde(rename = "signing_public_key")]
    SigningPublicKey,
    #[serde(rename = "version")]
    Version,
}

impl std::fmt::Display for PublicKeyFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            PublicKeyFields::JuiceboxConfig => "juicebox_config",
            PublicKeyFields::PublicKey => "public_key",
            PublicKeyFields::SigningPublicKey => "signing_public_key",
            PublicKeyFields::Version => "version",
        })
    }
}

