// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PublicKeyFields {
    #[serde(rename = "juicebox_config")]
    JuiceboxConfig,
    #[serde(rename = "public_key")]
    PublicKey,
    #[serde(rename = "signing_public_key")]
    SigningPublicKey,
    #[serde(rename = "version")]
    Version,
}

