// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RulesCountFields {
    #[serde(rename = "all_project_client_apps")]
    AllProjectClientApps,
    #[serde(rename = "cap_per_client_app")]
    CapPerClientApp,
    #[serde(rename = "cap_per_project")]
    CapPerProject,
    #[serde(rename = "client_app_rules_count")]
    ClientAppRulesCount,
    #[serde(rename = "project_rules_count")]
    ProjectRulesCount,
}

impl std::fmt::Display for RulesCountFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RulesCountFields::AllProjectClientApps => "all_project_client_apps",
            RulesCountFields::CapPerClientApp => "cap_per_client_app",
            RulesCountFields::CapPerProject => "cap_per_project",
            RulesCountFields::ClientAppRulesCount => "client_app_rules_count",
            RulesCountFields::ProjectRulesCount => "project_rules_count",
        })
    }
}

