// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SpaceFields {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "creator_id")]
    CreatorId,
    #[serde(rename = "ended_at")]
    EndedAt,
    #[serde(rename = "host_ids")]
    HostIds,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "invited_user_ids")]
    InvitedUserIds,
    #[serde(rename = "is_ticketed")]
    IsTicketed,
    #[serde(rename = "lang")]
    Lang,
    #[serde(rename = "participant_count")]
    ParticipantCount,
    #[serde(rename = "scheduled_start")]
    ScheduledStart,
    #[serde(rename = "speaker_ids")]
    SpeakerIds,
    #[serde(rename = "started_at")]
    StartedAt,
    #[serde(rename = "state")]
    State,
    #[serde(rename = "subscriber_count")]
    SubscriberCount,
    #[serde(rename = "title")]
    Title,
    #[serde(rename = "topic_ids")]
    TopicIds,
    #[serde(rename = "updated_at")]
    UpdatedAt,
}

impl std::fmt::Display for SpaceFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            SpaceFields::CreatedAt => "created_at",
            SpaceFields::CreatorId => "creator_id",
            SpaceFields::EndedAt => "ended_at",
            SpaceFields::HostIds => "host_ids",
            SpaceFields::Id => "id",
            SpaceFields::InvitedUserIds => "invited_user_ids",
            SpaceFields::IsTicketed => "is_ticketed",
            SpaceFields::Lang => "lang",
            SpaceFields::ParticipantCount => "participant_count",
            SpaceFields::ScheduledStart => "scheduled_start",
            SpaceFields::SpeakerIds => "speaker_ids",
            SpaceFields::StartedAt => "started_at",
            SpaceFields::State => "state",
            SpaceFields::SubscriberCount => "subscriber_count",
            SpaceFields::Title => "title",
            SpaceFields::TopicIds => "topic_ids",
            SpaceFields::UpdatedAt => "updated_at",
        })
    }
}

