// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SpaceExpansions {
    #[serde(rename = "creator_id")]
    CreatorId,
    #[serde(rename = "host_ids")]
    HostIds,
    #[serde(rename = "invited_user_ids")]
    InvitedUserIds,
    #[serde(rename = "speaker_ids")]
    SpeakerIds,
    #[serde(rename = "topic_ids")]
    TopicIds,
}

