// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetFields {
    #[serde(rename = "article")]
    Article,
    #[serde(rename = "attachments")]
    Attachments,
    #[serde(rename = "author_id")]
    AuthorId,
    #[serde(rename = "card_uri")]
    CardUri,
    #[serde(rename = "community_id")]
    CommunityId,
    #[serde(rename = "context_annotations")]
    ContextAnnotations,
    #[serde(rename = "conversation_id")]
    ConversationId,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "display_text_range")]
    DisplayTextRange,
    #[serde(rename = "edit_controls")]
    EditControls,
    #[serde(rename = "edit_history_tweet_ids")]
    EditHistoryTweetIds,
    #[serde(rename = "entities")]
    Entities,
    #[serde(rename = "geo")]
    Geo,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "in_reply_to_user_id")]
    InReplyToUserId,
    #[serde(rename = "lang")]
    Lang,
    #[serde(rename = "matched_media_notes")]
    MatchedMediaNotes,
    #[serde(rename = "media_metadata")]
    MediaMetadata,
    #[serde(rename = "non_public_metrics")]
    NonPublicMetrics,
    #[serde(rename = "note_tweet")]
    NoteTweet,
    #[serde(rename = "organic_metrics")]
    OrganicMetrics,
    #[serde(rename = "possibly_sensitive")]
    PossiblySensitive,
    #[serde(rename = "promoted_metrics")]
    PromotedMetrics,
    #[serde(rename = "public_metrics")]
    PublicMetrics,
    #[serde(rename = "referenced_tweets")]
    ReferencedTweets,
    #[serde(rename = "reply_settings")]
    ReplySettings,
    #[serde(rename = "scopes")]
    Scopes,
    #[serde(rename = "source")]
    Source,
    #[serde(rename = "suggested_source_links")]
    SuggestedSourceLinks,
    #[serde(rename = "suggested_source_links_with_counts")]
    SuggestedSourceLinksWithCounts,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "withheld")]
    Withheld,
}

impl std::fmt::Display for TweetFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            TweetFields::Article => "article",
            TweetFields::Attachments => "attachments",
            TweetFields::AuthorId => "author_id",
            TweetFields::CardUri => "card_uri",
            TweetFields::CommunityId => "community_id",
            TweetFields::ContextAnnotations => "context_annotations",
            TweetFields::ConversationId => "conversation_id",
            TweetFields::CreatedAt => "created_at",
            TweetFields::DisplayTextRange => "display_text_range",
            TweetFields::EditControls => "edit_controls",
            TweetFields::EditHistoryTweetIds => "edit_history_tweet_ids",
            TweetFields::Entities => "entities",
            TweetFields::Geo => "geo",
            TweetFields::Id => "id",
            TweetFields::InReplyToUserId => "in_reply_to_user_id",
            TweetFields::Lang => "lang",
            TweetFields::MatchedMediaNotes => "matched_media_notes",
            TweetFields::MediaMetadata => "media_metadata",
            TweetFields::NonPublicMetrics => "non_public_metrics",
            TweetFields::NoteTweet => "note_tweet",
            TweetFields::OrganicMetrics => "organic_metrics",
            TweetFields::PossiblySensitive => "possibly_sensitive",
            TweetFields::PromotedMetrics => "promoted_metrics",
            TweetFields::PublicMetrics => "public_metrics",
            TweetFields::ReferencedTweets => "referenced_tweets",
            TweetFields::ReplySettings => "reply_settings",
            TweetFields::Scopes => "scopes",
            TweetFields::Source => "source",
            TweetFields::SuggestedSourceLinks => "suggested_source_links",
            TweetFields::SuggestedSourceLinksWithCounts => "suggested_source_links_with_counts",
            TweetFields::Text => "text",
            TweetFields::Withheld => "withheld",
        })
    }
}

