// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetExpansions {
    #[serde(rename = "article.cover_media")]
    ArticleCoverMedia,
    #[serde(rename = "article.media_entities")]
    ArticleMediaEntities,
    #[serde(rename = "attachments.media_keys")]
    AttachmentsMediaKeys,
    #[serde(rename = "attachments.media_source_tweet")]
    AttachmentsMediaSourceTweet,
    #[serde(rename = "attachments.poll_ids")]
    AttachmentsPollIds,
    #[serde(rename = "author_id")]
    AuthorId,
    #[serde(rename = "edit_history_tweet_ids")]
    EditHistoryTweetIds,
    #[serde(rename = "entities.mentions.username")]
    EntitiesMentionsUsername,
    #[serde(rename = "geo.place_id")]
    GeoPlaceId,
    #[serde(rename = "in_reply_to_user_id")]
    InReplyToUserId,
    #[serde(rename = "entities.note.mentions.username")]
    EntitiesNoteMentionsUsername,
    #[serde(rename = "referenced_tweets.id")]
    ReferencedTweetsId,
    #[serde(rename = "referenced_tweets.id.attachments.media_keys")]
    ReferencedTweetsIdAttachmentsMediaKeys,
    #[serde(rename = "referenced_tweets.id.author_id")]
    ReferencedTweetsIdAuthorId,
}

impl std::fmt::Display for TweetExpansions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            TweetExpansions::ArticleCoverMedia => "article.cover_media",
            TweetExpansions::ArticleMediaEntities => "article.media_entities",
            TweetExpansions::AttachmentsMediaKeys => "attachments.media_keys",
            TweetExpansions::AttachmentsMediaSourceTweet => "attachments.media_source_tweet",
            TweetExpansions::AttachmentsPollIds => "attachments.poll_ids",
            TweetExpansions::AuthorId => "author_id",
            TweetExpansions::EditHistoryTweetIds => "edit_history_tweet_ids",
            TweetExpansions::EntitiesMentionsUsername => "entities.mentions.username",
            TweetExpansions::GeoPlaceId => "geo.place_id",
            TweetExpansions::InReplyToUserId => "in_reply_to_user_id",
            TweetExpansions::EntitiesNoteMentionsUsername => "entities.note.mentions.username",
            TweetExpansions::ReferencedTweetsId => "referenced_tweets.id",
            TweetExpansions::ReferencedTweetsIdAttachmentsMediaKeys => "referenced_tweets.id.attachments.media_keys",
            TweetExpansions::ReferencedTweetsIdAuthorId => "referenced_tweets.id.author_id",
        })
    }
}

