// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UsageFields {
    #[serde(rename = "cap_reset_day")]
    CapResetDay,
    #[serde(rename = "daily_client_app_usage")]
    DailyClientAppUsage,
    #[serde(rename = "daily_project_usage")]
    DailyProjectUsage,
    #[serde(rename = "project_cap")]
    ProjectCap,
    #[serde(rename = "project_id")]
    ProjectId,
    #[serde(rename = "project_usage")]
    ProjectUsage,
}

