// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UsageFields {
    #[serde(rename = "cap_reset_day")]
    CapResetDay,
    #[serde(rename = "daily_client_app_usage")]
    DailyClientAppUsage,
    #[serde(rename = "daily_project_usage")]
    DailyProjectUsage,
    #[serde(rename = "project_cap")]
    ProjectCap,
    #[serde(rename = "project_id")]
    ProjectId,
    #[serde(rename = "project_usage")]
    ProjectUsage,
}

impl std::fmt::Display for UsageFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UsageFields::CapResetDay => "cap_reset_day",
            UsageFields::DailyClientAppUsage => "daily_client_app_usage",
            UsageFields::DailyProjectUsage => "daily_project_usage",
            UsageFields::ProjectCap => "project_cap",
            UsageFields::ProjectId => "project_id",
            UsageFields::ProjectUsage => "project_usage",
        })
    }
}

