// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserExpansions {
    #[serde(rename = "affiliation.user_id")]
    AffiliationUserId,
    #[serde(rename = "most_recent_tweet_id")]
    MostRecentTweetId,
    #[serde(rename = "pinned_tweet_id")]
    PinnedTweetId,
}

impl std::fmt::Display for UserExpansions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UserExpansions::AffiliationUserId => "affiliation.user_id",
            UserExpansions::MostRecentTweetId => "most_recent_tweet_id",
            UserExpansions::PinnedTweetId => "pinned_tweet_id",
        })
    }
}

