// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserFields {
    #[serde(rename = "affiliation")]
    Affiliation,
    #[serde(rename = "confirmed_email")]
    ConfirmedEmail,
    #[serde(rename = "connection_status")]
    ConnectionStatus,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "entities")]
    Entities,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "is_identity_verified")]
    IsIdentityVerified,
    #[serde(rename = "location")]
    Location,
    #[serde(rename = "most_recent_tweet_id")]
    MostRecentTweetId,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "parody")]
    Parody,
    #[serde(rename = "pinned_tweet_id")]
    PinnedTweetId,
    #[serde(rename = "profile_banner_url")]
    ProfileBannerUrl,
    #[serde(rename = "profile_image_url")]
    ProfileImageUrl,
    #[serde(rename = "protected")]
    Protected,
    #[serde(rename = "public_metrics")]
    PublicMetrics,
    #[serde(rename = "receives_your_dm")]
    ReceivesYourDm,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "subscription_type")]
    SubscriptionType,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "username")]
    Username,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "verified_followers_count")]
    VerifiedFollowersCount,
    #[serde(rename = "verified_type")]
    VerifiedType,
    #[serde(rename = "withheld")]
    Withheld,
}

impl std::fmt::Display for UserFields {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UserFields::Affiliation => "affiliation",
            UserFields::ConfirmedEmail => "confirmed_email",
            UserFields::ConnectionStatus => "connection_status",
            UserFields::CreatedAt => "created_at",
            UserFields::Description => "description",
            UserFields::Entities => "entities",
            UserFields::Id => "id",
            UserFields::IsIdentityVerified => "is_identity_verified",
            UserFields::Location => "location",
            UserFields::MostRecentTweetId => "most_recent_tweet_id",
            UserFields::Name => "name",
            UserFields::Parody => "parody",
            UserFields::PinnedTweetId => "pinned_tweet_id",
            UserFields::ProfileBannerUrl => "profile_banner_url",
            UserFields::ProfileImageUrl => "profile_image_url",
            UserFields::Protected => "protected",
            UserFields::PublicMetrics => "public_metrics",
            UserFields::ReceivesYourDm => "receives_your_dm",
            UserFields::Subscription => "subscription",
            UserFields::SubscriptionType => "subscription_type",
            UserFields::Url => "url",
            UserFields::Username => "username",
            UserFields::Verified => "verified",
            UserFields::VerifiedFollowersCount => "verified_followers_count",
            UserFields::VerifiedType => "verified_type",
            UserFields::Withheld => "withheld",
        })
    }
}

