// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserFields {
    #[serde(rename = "affiliation")]
    Affiliation,
    #[serde(rename = "confirmed_email")]
    ConfirmedEmail,
    #[serde(rename = "connection_status")]
    ConnectionStatus,
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "entities")]
    Entities,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "is_identity_verified")]
    IsIdentityVerified,
    #[serde(rename = "location")]
    Location,
    #[serde(rename = "most_recent_tweet_id")]
    MostRecentTweetId,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "parody")]
    Parody,
    #[serde(rename = "pinned_tweet_id")]
    PinnedTweetId,
    #[serde(rename = "profile_banner_url")]
    ProfileBannerUrl,
    #[serde(rename = "profile_image_url")]
    ProfileImageUrl,
    #[serde(rename = "protected")]
    Protected,
    #[serde(rename = "public_metrics")]
    PublicMetrics,
    #[serde(rename = "receives_your_dm")]
    ReceivesYourDm,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "subscription_type")]
    SubscriptionType,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "username")]
    Username,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "verified_followers_count")]
    VerifiedFollowersCount,
    #[serde(rename = "verified_type")]
    VerifiedType,
    #[serde(rename = "withheld")]
    Withheld,
}

