// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WebhookConfigFields {
    #[serde(rename = "created_at")]
    CreatedAt,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "valid")]
    Valid,
}

