// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/spaces — Get Spaces by IDs
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub ids: Vec<String>,
    #[serde(rename = "space.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub space_fields: Option<Vec<crate::x::params::space_fields_parameter::SpaceFields>>,
    #[serde(rename = "expansions", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub expansions: Option<Vec<crate::x::params::space_expansions_parameter::SpaceExpansions>>,
    #[serde(rename = "user.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub user_fields: Option<Vec<crate::x::params::user_fields_parameter::UserFields>>,
    #[serde(rename = "topic.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub topic_fields: Option<Vec<crate::x::params::topic_fields_parameter::TopicFields>>,
}

pub type Response = Get2SpacesResponse;

