// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/connections — Get Connection History
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<RequestStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub endpoints: Option<Vec<RequestEndpointsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pagination_token: Option<String>,
    #[serde(rename = "connection.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub connection_fields: Option<Vec<crate::x::params::connection_fields_parameter::ConnectionFields>>,
}

pub type Response = Get2ConnectionsResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "all")]
    All,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestEndpointsItem {
    #[serde(rename = "filtered_stream")]
    FilteredStream,
    #[serde(rename = "sample_stream")]
    SampleStream,
    #[serde(rename = "sample10_stream")]
    Sample10Stream,
    #[serde(rename = "firehose_stream")]
    FirehoseStream,
    #[serde(rename = "tweets_compliance_stream")]
    TweetsComplianceStream,
    #[serde(rename = "users_compliance_stream")]
    UsersComplianceStream,
    #[serde(rename = "tweet_label_stream")]
    TweetLabelStream,
    #[serde(rename = "firehose_stream_lang_en")]
    FirehoseStreamLangEn,
    #[serde(rename = "firehose_stream_lang_ja")]
    FirehoseStreamLangJa,
    #[serde(rename = "firehose_stream_lang_ko")]
    FirehoseStreamLangKo,
    #[serde(rename = "firehose_stream_lang_pt")]
    FirehoseStreamLangPt,
    #[serde(rename = "likes_firehose_stream")]
    LikesFirehoseStream,
    #[serde(rename = "likes_sample10_stream")]
    LikesSample10Stream,
    #[serde(rename = "likes_compliance_stream")]
    LikesComplianceStream,
}

