// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! POST /2/dm_conversations/{dm_conversation_id}/messages — Create DM message by conversation ID
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub dm_conversation_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<CreateMessageRequest>,
}

pub type Response = CreateDmEventResponse;

