// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/tweets.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/tweets
pub async fn get(
    http: &Http,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = "tweets";
    http.send_with_query(Method::GET, path, req).await
}

/// POST /2/tweets
pub async fn post(
    http: &Http,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = "tweets";
    http.send(Method::POST, path, Some(&req.body)).await
}

