// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! DELETE /2/activity/subscriptions — Delete X activity subscriptions by IDs
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    pub ids: Vec<ActivitySubscriptionId>,
}

pub type Response = ActivitySubscriptionDeleteResponse;

