// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/users/{source_user_id}/muting/{target_user_id}.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// DELETE /2/users/{source_user_id}/muting/{target_user_id}
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("users/{}/muting/{}", urlencoding::encode(&req.source_user_id.to_string()), urlencoding::encode(&req.target_user_id.to_string()));
    http.send::<_, ()>(Method::DELETE, &path, None).await
}

