// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/dm_conversations/with/{participant_id}/messages.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// POST /2/dm_conversations/with/{participant_id}/messages
pub async fn post(
    http: &Http,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = format!("dm_conversations/with/{}/messages", urlencoding::encode(&req.participant_id.to_string()));
    http.send(Method::POST, &path, req.body.as_ref()).await
}

