// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/users/{id}/public_keys — Get user public keys
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub id: UserId,
    #[serde(rename = "public_key.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub public_key_fields: Option<Vec<crate::x::params::public_key_fields_parameter::PublicKeyFields>>,
}

pub type Response = Get2UsersIdPublicKeysResponse;

