// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/chat/media/{id}/{media_hash_key} — Download Chat Media
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub id: ChatConversationOrRecipientId,
    #[serde(skip_serializing)]
    pub media_hash_key: MediaHashKey,
}

/// 204 No Content / no body / non-JSON response.
#[derive(Debug, Clone, Default)]
pub struct Response;

