// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/trends/by/woeid/{woeid} — Get Trends by WOEID
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub woeid: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_trends: Option<i32>,
    #[serde(rename = "trend.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub trend_fields: Option<Vec<crate::x::params::trend_fields_parameter::TrendFields>>,
}

pub type Response = Get2TrendsByWoeidWoeidResponse;

