#![allow(non_camel_case_types, non_snake_case, dead_code)]

pub mod serde_helpers;
pub mod types;
pub mod params;
pub mod error;
pub mod http;
pub mod mock;

pub use error::Error;

// Spec-derived endpoint module declarations live in codegen.rs and are
// re-exported here. Regenerated by `python x-api-spec/codegen.py`; this
// file stays hand-written so adding/removing endpoints in the spec
// never requires editing mod.rs.
mod codegen;
pub use codegen::*;
