// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/account_activity/webhooks/{webhook_id}/subscriptions/{user_id}/all.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// DELETE /2/account_activity/webhooks/{webhook_id}/subscriptions/{user_id}/all
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("account_activity/webhooks/{}/subscriptions/{}/all", urlencoding::encode(&req.webhook_id.to_string()), urlencoding::encode(&req.user_id.to_string()));
    http.send::<_, ()>(Method::DELETE, &path, None).await
}

