// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/insights/historical — Get historical Post insights
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    pub tweet_ids: Vec<TweetId>,
    pub end_time: chrono::DateTime<chrono::Utc>,
    pub start_time: chrono::DateTime<chrono::Utc>,
    pub granularity: RequestGranularity,
    pub requested_metrics: Vec<RequestRequestedMetricsItem>,
    #[serde(rename = "engagement.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub engagement_fields: Option<Vec<crate::x::params::engagement_fields_parameter::EngagementFields>>,
}

pub type Response = Get2InsightsHistoricalResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestGranularity {
    #[serde(rename = "Daily")]
    Daily,
    #[serde(rename = "Hourly")]
    Hourly,
    #[serde(rename = "Weekly")]
    Weekly,
    #[serde(rename = "Total")]
    Total,
}

impl std::fmt::Display for RequestGranularity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestGranularity::Daily => "Daily",
            RequestGranularity::Hourly => "Hourly",
            RequestGranularity::Weekly => "Weekly",
            RequestGranularity::Total => "Total",
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRequestedMetricsItem {
    #[serde(rename = "AppInstallAttempts")]
    AppInstallAttempts,
    #[serde(rename = "AppOpens")]
    AppOpens,
    #[serde(rename = "DetailExpands")]
    DetailExpands,
    #[serde(rename = "EmailTweet")]
    EmailTweet,
    #[serde(rename = "Engagements")]
    Engagements,
    #[serde(rename = "Follows")]
    Follows,
    #[serde(rename = "HashtagClicks")]
    HashtagClicks,
    #[serde(rename = "Impressions")]
    Impressions,
    #[serde(rename = "Likes")]
    Likes,
    #[serde(rename = "LinkClicks")]
    LinkClicks,
    #[serde(rename = "MediaEngagements")]
    MediaEngagements,
    #[serde(rename = "MediaViews")]
    MediaViews,
    #[serde(rename = "PermalinkClicks")]
    PermalinkClicks,
    #[serde(rename = "ProfileVisits")]
    ProfileVisits,
    #[serde(rename = "QuoteTweets")]
    QuoteTweets,
    #[serde(rename = "Replies")]
    Replies,
    #[serde(rename = "Retweets")]
    Retweets,
    #[serde(rename = "UniqueVideoViews")]
    UniqueVideoViews,
    #[serde(rename = "UrlClicks")]
    UrlClicks,
    #[serde(rename = "UserProfileClicks")]
    UserProfileClicks,
    #[serde(rename = "VideoCompletions")]
    VideoCompletions,
    #[serde(rename = "VideoPlayed25Percent")]
    VideoPlayed25Percent,
    #[serde(rename = "VideoPlayed50Percent")]
    VideoPlayed50Percent,
    #[serde(rename = "VideoPlayed75Percent")]
    VideoPlayed75Percent,
    #[serde(rename = "VideoStarts")]
    VideoStarts,
    #[serde(rename = "VideoViews")]
    VideoViews,
}

impl std::fmt::Display for RequestRequestedMetricsItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestRequestedMetricsItem::AppInstallAttempts => "AppInstallAttempts",
            RequestRequestedMetricsItem::AppOpens => "AppOpens",
            RequestRequestedMetricsItem::DetailExpands => "DetailExpands",
            RequestRequestedMetricsItem::EmailTweet => "EmailTweet",
            RequestRequestedMetricsItem::Engagements => "Engagements",
            RequestRequestedMetricsItem::Follows => "Follows",
            RequestRequestedMetricsItem::HashtagClicks => "HashtagClicks",
            RequestRequestedMetricsItem::Impressions => "Impressions",
            RequestRequestedMetricsItem::Likes => "Likes",
            RequestRequestedMetricsItem::LinkClicks => "LinkClicks",
            RequestRequestedMetricsItem::MediaEngagements => "MediaEngagements",
            RequestRequestedMetricsItem::MediaViews => "MediaViews",
            RequestRequestedMetricsItem::PermalinkClicks => "PermalinkClicks",
            RequestRequestedMetricsItem::ProfileVisits => "ProfileVisits",
            RequestRequestedMetricsItem::QuoteTweets => "QuoteTweets",
            RequestRequestedMetricsItem::Replies => "Replies",
            RequestRequestedMetricsItem::Retweets => "Retweets",
            RequestRequestedMetricsItem::UniqueVideoViews => "UniqueVideoViews",
            RequestRequestedMetricsItem::UrlClicks => "UrlClicks",
            RequestRequestedMetricsItem::UserProfileClicks => "UserProfileClicks",
            RequestRequestedMetricsItem::VideoCompletions => "VideoCompletions",
            RequestRequestedMetricsItem::VideoPlayed25Percent => "VideoPlayed25Percent",
            RequestRequestedMetricsItem::VideoPlayed50Percent => "VideoPlayed50Percent",
            RequestRequestedMetricsItem::VideoPlayed75Percent => "VideoPlayed75Percent",
            RequestRequestedMetricsItem::VideoStarts => "VideoStarts",
            RequestRequestedMetricsItem::VideoViews => "VideoViews",
        })
    }
}

