// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/dm_conversations/{id}/dm_events — Get DM events for a DM conversation
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub id: DmConversationId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pagination_token: Option<PaginationToken32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<RequestEventTypesItem>>,
    #[serde(rename = "dm_event.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub dm_event_fields: Option<Vec<crate::x::params::dm_event_fields_parameter::DmEventFields>>,
    #[serde(rename = "expansions", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub expansions: Option<Vec<crate::x::params::dm_event_expansions_parameter::DmEventExpansions>>,
    #[serde(rename = "media.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub media_fields: Option<Vec<crate::x::params::media_fields_parameter::MediaFields>>,
    #[serde(rename = "user.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub user_fields: Option<Vec<crate::x::params::user_fields_parameter::UserFields>>,
    #[serde(rename = "tweet.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub tweet_fields: Option<Vec<crate::x::params::tweet_fields_parameter::TweetFields>>,
}

pub type Response = Get2DmConversationsIdDmEventsResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestEventTypesItem {
    #[serde(rename = "MessageCreate")]
    MessageCreate,
    #[serde(rename = "ParticipantsJoin")]
    ParticipantsJoin,
    #[serde(rename = "ParticipantsLeave")]
    ParticipantsLeave,
}

impl std::fmt::Display for RequestEventTypesItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestEventTypesItem::MessageCreate => "MessageCreate",
            RequestEventTypesItem::ParticipantsJoin => "ParticipantsJoin",
            RequestEventTypesItem::ParticipantsLeave => "ParticipantsLeave",
        })
    }
}

