// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/tweets/{tweet_id}/hidden.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// PUT /2/tweets/{tweet_id}/hidden
pub async fn put(
    http: &Http,
    req: &super::put::Request,
) -> Result<super::put::Response, Error> {
    let path = format!("tweets/{}/hidden", urlencoding::encode(&req.tweet_id.to_string()));
    http.send(Method::PUT, &path, req.body.as_ref()).await
}

