// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! PUT /2/tweets/{tweet_id}/hidden — Hide reply
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub tweet_id: TweetId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<TweetHideRequest>,
}

pub type Response = TweetHideResponse;

