// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/activity/subscriptions/{subscription_id}.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// PUT /2/activity/subscriptions/{subscription_id}
pub async fn put(
    http: &Http,
    req: &super::put::Request,
) -> Result<super::put::Response, Error> {
    let path = format!("activity/subscriptions/{}", urlencoding::encode(&req.subscription_id.to_string()));
    http.send(Method::PUT, &path, req.body.as_ref()).await
}

/// DELETE /2/activity/subscriptions/{subscription_id}
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("activity/subscriptions/{}", urlencoding::encode(&req.subscription_id.to_string()));
    http.send::<_, ()>(Method::DELETE, &path, None).await
}

