// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! PUT /2/activity/subscriptions/{subscription_id} — Update X activity subscription
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub subscription_id: ActivitySubscriptionId,
    #[serde(skip_serializing)]
    pub body: Option<ActivitySubscriptionUpdateRequest>,
}

pub type Response = ActivitySubscriptionUpdateResponse;

