// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionCreateRequest {
    pub event_type: ActivitySubscriptionCreateRequestEventType,
    pub filter: ActivitySubscriptionFilter,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<WebhookConfigId>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ActivitySubscriptionCreateRequestEventType {
    #[serde(rename = "profile.update.bio")]
    ProfileUpdateBio,
    #[serde(rename = "profile.update.profile_picture")]
    ProfileUpdateProfilePicture,
    #[serde(rename = "profile.update.banner_picture")]
    ProfileUpdateBannerPicture,
    #[serde(rename = "profile.update.screenname")]
    ProfileUpdateScreenname,
    #[serde(rename = "profile.update.geo")]
    ProfileUpdateGeo,
    #[serde(rename = "profile.update.url")]
    ProfileUpdateUrl,
    #[serde(rename = "profile.update.verified_badge")]
    ProfileUpdateVerifiedBadge,
    #[serde(rename = "profile.update.affiliate_badge")]
    ProfileUpdateAffiliateBadge,
    #[serde(rename = "profile.update.handle")]
    ProfileUpdateHandle,
    #[serde(rename = "news.new")]
    NewsNew,
    #[serde(rename = "follow.follow")]
    FollowFollow,
    #[serde(rename = "follow.unfollow")]
    FollowUnfollow,
    #[serde(rename = "spaces.start")]
    SpacesStart,
    #[serde(rename = "spaces.end")]
    SpacesEnd,
    #[serde(rename = "chat.received")]
    ChatReceived,
    #[serde(rename = "chat.sent")]
    ChatSent,
    #[serde(rename = "chat.conversation_join")]
    ChatConversationJoin,
    #[serde(rename = "dm.sent")]
    DmSent,
    #[serde(rename = "dm.received")]
    DmReceived,
    #[serde(rename = "dm.indicate_typing")]
    DmIndicateTyping,
    #[serde(rename = "dm.read")]
    DmRead,
}

impl std::fmt::Display for ActivitySubscriptionCreateRequestEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateBio => "profile.update.bio",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateProfilePicture => "profile.update.profile_picture",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateBannerPicture => "profile.update.banner_picture",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateScreenname => "profile.update.screenname",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateGeo => "profile.update.geo",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateUrl => "profile.update.url",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateVerifiedBadge => "profile.update.verified_badge",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateAffiliateBadge => "profile.update.affiliate_badge",
            ActivitySubscriptionCreateRequestEventType::ProfileUpdateHandle => "profile.update.handle",
            ActivitySubscriptionCreateRequestEventType::NewsNew => "news.new",
            ActivitySubscriptionCreateRequestEventType::FollowFollow => "follow.follow",
            ActivitySubscriptionCreateRequestEventType::FollowUnfollow => "follow.unfollow",
            ActivitySubscriptionCreateRequestEventType::SpacesStart => "spaces.start",
            ActivitySubscriptionCreateRequestEventType::SpacesEnd => "spaces.end",
            ActivitySubscriptionCreateRequestEventType::ChatReceived => "chat.received",
            ActivitySubscriptionCreateRequestEventType::ChatSent => "chat.sent",
            ActivitySubscriptionCreateRequestEventType::ChatConversationJoin => "chat.conversation_join",
            ActivitySubscriptionCreateRequestEventType::DmSent => "dm.sent",
            ActivitySubscriptionCreateRequestEventType::DmReceived => "dm.received",
            ActivitySubscriptionCreateRequestEventType::DmIndicateTyping => "dm.indicate_typing",
            ActivitySubscriptionCreateRequestEventType::DmRead => "dm.read",
        })
    }
}

