// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionDeleteResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ActivitySubscriptionDeleteResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<ActivitySubscriptionDeleteResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionDeleteResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionDeleteResponseMeta {
    /// Number of active subscriptions remaining.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_subscriptions: Option<i32>,
}

