// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// An activity event or error that can be returned by the x activity streaming API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityStreamingResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ActivityStreamingResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityStreamingResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_uuid: Option<ActivityEventId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filter: Option<ActivitySubscriptionFilter>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<ActivityStreamingResponsePayload>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

