// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// An XActivity subscription.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscription {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub event_type: String,
    pub filter: ActivitySubscriptionFilter,
    pub subscription_id: ActivitySubscriptionId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<WebhookConfigId>,
}

