// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionGetResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<ActivitySubscription>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<ActivitySubscriptionGetResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionGetResponseMeta {
    /// Token to retrieve the next page of results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    /// Number of active subscriptions returned in response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_count: Option<i32>,
}

