// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "event_type")]
pub enum ActivityStreamingResponsePayload {
    #[serde(rename = "follow.follow")]
    FollowFollow(FollowActivityResponsePayload),
    #[serde(rename = "follow.unfollow")]
    FollowUnfollow(FollowActivityResponsePayload),
    #[serde(rename = "news.new")]
    NewsNew(NewsActivityResponsePayload),
    #[serde(rename = "profile.update.affiliate_badge")]
    ProfileUpdateAffiliateBadge(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.banner_picture")]
    ProfileUpdateBannerPicture(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.bio")]
    ProfileUpdateBio(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.geo")]
    ProfileUpdateGeo(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.handle")]
    ProfileUpdateHandle(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.profile_picture")]
    ProfileUpdateProfilePicture(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.screenname")]
    ProfileUpdateScreenname(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.url")]
    ProfileUpdateUrl(ProfileUpdateActivityResponsePayload),
    #[serde(rename = "profile.update.verified_badge")]
    ProfileUpdateVerifiedBadge(ProfileUpdateActivityResponsePayload),
}

