// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionUpdateResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ActivitySubscriptionUpdateResponseData>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivitySubscriptionUpdateResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription: Option<ActivitySubscription>,
    /// Number of active subscriptions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_subscriptions: Option<i32>,
}

