// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A response from modifying user-specified stream filtering rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddOrDeleteRulesResponse {
    /// All user-specified stream filtering rules that were created.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<Rule>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    pub meta: RulesResponseMetadata,
}

