// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A request to add a user-specified stream filtering rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddRulesRequest {
    pub add: Vec<RuleNoId>,
}

