// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Client App Rule Counts for all applications in the project
pub type AllProjectClientApps = Vec<AppRulesCount>;

/// Represent a boundary range (start and end zero-based indices) for the portion of text that is displayed for a post. `start` must be smaller than `end`. The start index is inclusive, the end index is exclusive.
pub type DisplayTextRange = Vec<i32>;

/// Attachments to a DM Event.
pub type DmAttachments = Vec<DmMediaAttachment>;

/// Participants for the DM Conversation.
pub type DmParticipants = Vec<UserId>;

/// A [GeoJson Position](https://tools.ietf.org/html/rfc7946#section-3.1.1) in the format `[longitude,latitude]`.
pub type Position = Vec<f64>;

/// An array of all available variants of the media.
pub type Variants = Vec<Variant>;

