// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A count of user-provided stream filtering rules at the client application level.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppRulesCount {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_app_id: Option<ClientAppId>,
    /// Number of rules for client application
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_count: Option<i32>,
}

