// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudiencePolicy {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub creator_subscriptions: Option<Vec<AudiencePolicyCreatorSubscriptionsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_subscriptions: Option<Vec<AudiencePolicyXSubscriptionsItem>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AudiencePolicyCreatorSubscriptionsItem {
    #[serde(rename = "Any")]
    Any,
}

impl std::fmt::Display for AudiencePolicyCreatorSubscriptionsItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            AudiencePolicyCreatorSubscriptionsItem::Any => "Any",
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AudiencePolicyXSubscriptionsItem {
    #[serde(rename = "Any")]
    Any,
}

impl std::fmt::Display for AudiencePolicyXSubscriptionsItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            AudiencePolicyXSubscriptionsItem::Any => "Any",
        })
    }
}

