// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BookmarkFolderPostsResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<BookmarkFolderPostsResponseDataItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<BookmarkFolderPostsResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BookmarkFolderPostsResponseDataItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<TweetId>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BookmarkFolderPostsResponseMeta {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<NextToken>,
}

