// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Request body for initializing a Chat media upload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadInitializeRequest {
    /// XChat conversation identifier for the upload.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Total size of the media upload in bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<i32>,
}

