// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A Chat conversation resource representing either a direct or group conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatConversation {
    /// User IDs of group admins. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub admin_ids: Option<Vec<String>>,
    /// ISO 8601 timestamp when the group was created. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// URL for the group avatar. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_avatar_url: Option<String>,
    /// Encrypted group name. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// The unique identifier for this conversation.
    pub id: String,
    /// Whether notifications are muted for this conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_muted: Option<bool>,
    /// User IDs of group members. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member_ids: Option<Vec<String>>,
    /// Message time-to-live in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_ttl_msec: Option<String>,
    /// Array of user IDs who are participants in this conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participant_ids: Option<Vec<String>>,
    /// Whether screen capture blocking is enabled for this conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_capture_blocking_enabled: Option<bool>,
    /// Whether screen capture detection is enabled for this conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen_capture_detection_enabled: Option<bool>,
    /// The type of conversation: 'direct' or 'group'.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<ChatConversationType>,
    /// ISO 8601 timestamp when the group was last updated. Only present for group conversations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}


/// The type of conversation: 'direct' or 'group'.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChatConversationType {
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "group")]
    Group,
}

impl std::fmt::Display for ChatConversationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ChatConversationType::Direct => "direct",
            ChatConversationType::Group => "group",
        })
    }
}

