// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatInitializeConversationKeysRequest {
    /// Cryptographic signatures for the key initialization action.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_signatures: Option<Vec<ChatActionSignature>>,
    /// Base64-encoded key rotation payload for ratchet tree key management.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base64_encoded_key_rotation: Option<String>,
    /// Version of the conversation encryption key (typically a timestamp in milliseconds).
    pub conversation_key_version: String,
    /// The conversation key encrypted for each participant using their public key.
    pub conversation_participant_keys: Vec<ChatConversationParticipantKey>,
}

