// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// An Chat message event with extracted envelope fields and the original encoded event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessageEvent {
    /// The conversation ID this message belongs to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// The conversation token for this message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_token: Option<String>,
    /// The creation timestamp in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at_msec: Option<String>,
    /// Base64-encoded MessageEvent for client decoding.
    pub encoded_event: String,
    /// The unique identifier for this message event (message_id).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether the message is from a trusted source.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_trusted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_event_signature: Option<ChatMessageEventSignature>,
    /// The sequence ID of the previous message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_sequence_id: Option<String>,
    /// The user ID of the message sender.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender_id: Option<String>,
    /// The sequence identifier for ordering messages.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence_id: Option<String>,
}

