// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatAddGroupMembersResponse {
    /// Sequence ID of the conversation key change event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_key_change_sequence_id: Option<String>,
    /// List of all current member IDs in the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_member_ids: Option<Vec<String>>,
}

