// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Response from initializing a Chat media upload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadInitializeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ChatMediaUploadInitializeResponseData>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadInitializeResponseData {
    /// Conversation id associated with the upload.
    pub conversation_id: String,
    /// Media hash key returned by XChat.
    pub media_hash_key: String,
    /// Resume/session id for the upload.
    pub session_id: String,
}

