// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A participant's encrypted conversation key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatConversationParticipantKey {
    /// Conversation key encrypted with this participant's public key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encrypted_conversation_key: Option<String>,
    /// Version of the participant's public key used for encryption.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_key_version: Option<String>,
    /// Participant user ID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

