// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatMediaUploadAppendRequest {
    ChatMediaUploadAppendRequestVariant0(ChatMediaUploadAppendRequestVariant0),
    ChatMediaUploadAppendRequestVariant1(ChatMediaUploadAppendRequestVariant1),
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadAppendRequestVariant0 {
    /// XChat conversation identifier for the upload.
    pub conversation_id: String,
    pub media: MediaPayloadBinary,
    /// Media hash key returned from initialize.
    pub media_hash_key: String,
    pub segment_index: MediaSegments,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadAppendRequestVariant1 {
    /// XChat conversation identifier for the upload.
    pub conversation_id: String,
    pub media: MediaPayloadByte,
    /// Media hash key returned from initialize.
    pub media_hash_key: String,
    pub segment_index: MediaSegments,
}

