// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Message event signature for verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessageEventSignature {
    /// List of signing key information for message verification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_signing_key_info_list: Option<Vec<ChatMessageSigningKeyInfo>>,
    /// The version of the public key used for signing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_key_version: Option<String>,
    /// The signature of the message event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    /// The version of the signature algorithm.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature_version: Option<String>,
    /// The public key used for signing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signing_public_key: Option<String>,
}

