// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Request body for finalizing a Chat media upload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMediaUploadFinalizeRequest {
    /// XChat conversation identifier for the upload.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Media hash key returned from initialize.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_hash_key: Option<String>,
    /// Optional message identifier associated with the upload.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    /// Total number of uploaded parts as a numeric string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_parts: Option<String>,
    /// Optional TTL for the media in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ttl_msec: Option<String>,
}

