// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Key recovery configuration for Juicebox-based key storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatJuiceboxConfig {
    /// Raw JSON for key recovery configuration.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_store_token_map_json: Option<String>,
    /// Maximum guess count for key recovery.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_guess_count: Option<i32>,
    /// Serialized realm state for key recovery.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub realm_state_string: Option<String>,
    /// Threshold required to recover the key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recover_threshold: Option<i32>,
    /// Threshold required to register the key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub register_threshold: Option<i32>,
    /// Per-realm auth tokens for key recovery.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_map: Option<Vec<ChatJuiceboxConfigTokenMapItem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatJuiceboxConfigTokenMapItem {
    /// Realm identifier.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Realm connection details.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<ChatJuiceboxConfigTokenMapItemValue>,
}

/// Realm connection details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatJuiceboxConfigTokenMapItemValue {
    /// Realm URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Realm public key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    /// JWT auth token for the realm.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

