// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatGetConversationResponse {
    /// List of message events in the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<ChatMessageEvent>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<ChatGetConversationResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatGetConversationResponseMeta {
    /// Conversation key change events needed for decryption.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_key_events: Option<Vec<String>>,
    /// Whether there are more messages to fetch.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Token to retrieve the next page of results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    /// The number of message events returned.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_count: Option<i32>,
}

