// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatSendMessageResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ChatSendMessageResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatSendMessageResponseData {
    /// Base64-encoded response message event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encoded_message_event: Option<String>,
}

