// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatInitializeConversationKeysResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ChatInitializeConversationKeysResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatInitializeConversationKeysResponseData {
    /// Sequence ID of the conversation key change event. Use this to track key changes in the conversation event stream.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence_id: Option<String>,
}

