// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatAddGroupMembersRequest {
    /// Cryptographic signatures for the add-members action.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_signatures: Option<Vec<ChatActionSignature>>,
    /// Version of the new rotated conversation key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_key_version: Option<String>,
    /// Encrypted conversation keys for each new participant after key rotation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_participant_keys: Option<Vec<ChatConversationParticipantKey>>,
    /// Re-encrypted group avatar URL with new conversation key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encrypted_avatar_url: Option<String>,
    /// Re-encrypted group title with new conversation key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encrypted_title: Option<String>,
    /// List of user IDs to add to the group conversation.
    pub user_ids: Vec<String>,
}

