// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCreateConversationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<ChatCreateConversationResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCreateConversationResponseData {
    /// The ID of the created conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Sequence ID of the conversation key change event, if applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_key_change_sequence_id: Option<String>,
}

