// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCreateConversationRequest {
    /// Cryptographic signatures for the create action.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_signatures: Option<Vec<ChatActionSignature>>,
    /// Base64-encoded key rotation payload.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base64_encoded_key_rotation: Option<String>,
    /// Client-generated conversation ID.
    pub conversation_id: String,
    /// Version of the conversation encryption key.
    pub conversation_key_version: String,
    /// Encrypted conversation keys for each participant.
    pub conversation_participant_keys: Vec<ChatConversationParticipantKey>,
    /// User IDs of group admins. Defaults to the creator if omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_admins: Option<Vec<String>>,
    /// URL of the avatar image for the group conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_avatar_url: Option<String>,
    /// Description for the group conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_description: Option<String>,
    /// User IDs of group members to include in the conversation.
    pub group_members: Vec<String>,
    /// Display name for the group conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// Message time-to-live in milliseconds. Messages expire after this duration.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ttl_msec: Option<String>,
}

