// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatGetConversationsResponse {
    /// List of conversations in the user's inbox.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<ChatConversation>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub includes: Option<Expansions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<ChatGetConversationsResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatGetConversationsResponseMeta {
    /// Whether the user has pending message requests.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_message_requests: Option<bool>,
    /// Whether there are more conversations to fetch.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
    /// Token to retrieve the next page of results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    /// The number of conversations returned.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_count: Option<i32>,
}

