// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Signing key information for message verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessageSigningKeyInfo {
    /// The member ID associated with this signing key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    /// The version of the public key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_key_version: Option<String>,
    /// The signing public key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signing_public_key: Option<String>,
}

