// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceJob {
    pub created_at: CreatedAt,
    pub download_expires_at: DownloadExpiration,
    pub download_url: DownloadUrl,
    pub id: JobId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<ComplianceJobName>,
    pub status: ComplianceJobStatus,
    #[serde(rename = "type")]
    pub type_: ComplianceJobType,
    pub upload_expires_at: UploadExpiration,
    pub upload_url: UploadUrl,
}

