// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionExceptionProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connection_issue: Option<ConnectionExceptionProblemConnectionIssue>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ConnectionExceptionProblemConnectionIssue {
    #[serde(rename = "TooManyConnections")]
    TooManyConnections,
    #[serde(rename = "ProvisioningSubscription")]
    ProvisioningSubscription,
    #[serde(rename = "RuleConfigurationIssue")]
    RuleConfigurationIssue,
    #[serde(rename = "RulesInvalidIssue")]
    RulesInvalidIssue,
}

impl std::fmt::Display for ConnectionExceptionProblemConnectionIssue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            ConnectionExceptionProblemConnectionIssue::TooManyConnections => "TooManyConnections",
            ConnectionExceptionProblemConnectionIssue::ProvisioningSubscription => "ProvisioningSubscription",
            ConnectionExceptionProblemConnectionIssue::RuleConfigurationIssue => "RuleConfigurationIssue",
            ConnectionExceptionProblemConnectionIssue::RulesInvalidIssue => "RulesInvalidIssue",
        })
    }
}

