// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Connection {
    /// The IP address of the connected client.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_ip: Option<String>,
    /// The timestamp when the connection was established.
    pub connected_at: chrono::DateTime<chrono::Utc>,
    /// The reason for disconnection, if the connection is inactive.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disconnect_reason: Option<String>,
    /// The timestamp when the connection was disconnected, if applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disconnected_at: Option<chrono::DateTime<chrono::Utc>>,
    /// The name of the streaming endpoint.
    pub endpoint_name: String,
}

