// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represents the data for the context annotation entity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextAnnotationEntityFields {
    /// Description of the context annotation entity.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The unique id for a context annotation entity.
    pub id: String,
    /// Name of the context annotation entity.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

