// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Annotation inferred from the Tweet text.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextAnnotation {
    pub domain: ContextAnnotationDomainFields,
    pub entity: ContextAnnotationEntityFields,
}

