// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateDmConversationRequest {
    /// The conversation type that is being created.
    pub conversation_type: CreateDmConversationRequestConversationType,
    pub message: CreateMessageRequest,
    pub participant_ids: DmParticipants,
}


/// The conversation type that is being created.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CreateDmConversationRequestConversationType {
    #[serde(rename = "Group")]
    Group,
}

impl std::fmt::Display for CreateDmConversationRequestConversationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            CreateDmConversationRequestConversationType::Group => "Group",
        })
    }
}

