// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A request to create a new batch compliance job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateComplianceJobRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<ComplianceJobName>,
    /// If true, this endpoint will return a pre-signed URL with resumable uploads enabled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resumable: Option<bool>,
    /// Type of compliance job to list.
    #[serde(rename = "type")]
    pub type_: CreateComplianceJobRequestType,
}


/// Type of compliance job to list.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CreateComplianceJobRequestType {
    #[serde(rename = "tweets")]
    Tweets,
    #[serde(rename = "users")]
    Users,
}

