// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DmEvent {
    /// Specifies the type of attachments (if any) present in this DM.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<DmEventAttachments>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cashtags: Option<Vec<CashtagEntity>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dm_conversation_id: Option<DmConversationId>,
    pub event_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hashtags: Option<Vec<HashtagEntity>>,
    pub id: DmEventId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<MentionEntity>>,
    /// A list of participants for a ParticipantsJoin or ParticipantsLeave event_type.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participant_ids: Option<Vec<UserId>>,
    /// A list of Posts this DM refers to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub referenced_tweets: Option<Vec<DmEventReferencedTweetsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender_id: Option<UserId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<UrlEntityDm>>,
}


/// Specifies the type of attachments (if any) present in this DM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DmEventAttachments {
    /// A list of card IDs (if cards are attached).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_ids: Option<Vec<String>>,
    /// A list of Media Keys for each one of the media attachments (if media are attached).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_keys: Option<Vec<MediaKey>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DmEventReferencedTweetsItem {
    pub id: TweetId,
}

