// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// An Engagement Api Response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Engagement {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<EngagementErrorsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub measurement: Option<EngagementMeasurement>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementErrorsItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tweets: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurement {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics_time_series: Option<Vec<EngagementMeasurementMetricsTimeSeriesItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics_total: Option<Vec<EngagementMeasurementMetricsTotalItem>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTimeSeriesItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tweet_id: Option<TweetId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<EngagementMeasurementMetricsTimeSeriesItemValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTotalItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tweet_id: Option<TweetId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<Vec<EngagementMeasurementMetricsTotalItemValueItem>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTimeSeriesItemValue {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_values: Option<Vec<EngagementMeasurementMetricsTimeSeriesItemValueMetricValuesItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<EngagementMeasurementMetricsTimeSeriesItemValueTimestamp>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTotalItemValueItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_value: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTimeSeriesItemValueMetricValuesItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metric_value: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngagementMeasurementMetricsTimeSeriesItemValueTimestamp {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub iso8601_time: Option<String>,
}

