// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

use serde::{Deserialize, Serialize};

/// Status of a compliance job.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ComplianceJobStatus {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "expired")]
    Expired,
}

/// Type of compliance job to list.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ComplianceJobType {
    #[serde(rename = "tweets")]
    Tweets,
    #[serde(rename = "users")]
    Users,
}

/// A string enum value which identifies a media use-case. This identifier is used to enforce use-case specific constraints (e.g. file size, video duration) and enable advanced features.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaCategory {
    #[serde(rename = "amplify_video")]
    AmplifyVideo,
    #[serde(rename = "tweet_gif")]
    TweetGif,
    #[serde(rename = "tweet_image")]
    TweetImage,
    #[serde(rename = "tweet_video")]
    TweetVideo,
    #[serde(rename = "dm_gif")]
    DmGif,
    #[serde(rename = "dm_image")]
    DmImage,
    #[serde(rename = "dm_video")]
    DmVideo,
    #[serde(rename = "subtitles")]
    Subtitles,
}

/// A string enum value which identifies a media use-case. This identifier is used to enforce use-case specific constraints (e.g. file size) and enable advanced features.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaCategoryOneShot {
    #[serde(rename = "tweet_image")]
    TweetImage,
    #[serde(rename = "dm_image")]
    DmImage,
    #[serde(rename = "subtitles")]
    Subtitles,
}

/// The media category of uploaded media to which subtitles should be added/deleted
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaCategorySubtitles {
    #[serde(rename = "AmplifyVideo")]
    AmplifyVideo,
    #[serde(rename = "TweetVideo")]
    TweetVideo,
}

/// Community Note misleading tags type.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MisleadingTags {
    #[serde(rename = "disputed_claim_as_fact")]
    DisputedClaimAsFact,
    #[serde(rename = "factual_error")]
    FactualError,
    #[serde(rename = "manipulated_media")]
    ManipulatedMedia,
    #[serde(rename = "misinterpreted_satire")]
    MisinterpretedSatire,
    #[serde(rename = "missing_important_context")]
    MissingImportantContext,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "outdated_information")]
    OutdatedInformation,
}

/// Community Note classification type.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NoteClassification {
    #[serde(rename = "misinformed_or_potentially_misleading")]
    MisinformedOrPotentiallyMisleading,
    #[serde(rename = "not_misleading")]
    NotMisleading,
}

/// Community Note rating status
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NoteRatingStatus {
    #[serde(rename = "currently_rated_helpful")]
    CurrentlyRatedHelpful,
    #[serde(rename = "currently_rated_not_helpful")]
    CurrentlyRatedNotHelpful,
    #[serde(rename = "firm_reject")]
    FirmReject,
    #[serde(rename = "insufficient_consensus")]
    InsufficientConsensus,
    #[serde(rename = "minimum_ratings_not_met")]
    MinimumRatingsNotMet,
    #[serde(rename = "needs_more_ratings")]
    NeedsMoreRatings,
    #[serde(rename = "needs_your_help")]
    NeedsYourHelp,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlaceType {
    #[serde(rename = "poi")]
    Poi,
    #[serde(rename = "neighborhood")]
    Neighborhood,
    #[serde(rename = "city")]
    City,
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "country")]
    Country,
    #[serde(rename = "unknown")]
    Unknown,
}

/// Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReplySettings {
    #[serde(rename = "everyone")]
    Everyone,
    #[serde(rename = "mentionedUsers")]
    MentionedUsers,
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "other")]
    Other,
}

/// Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, subscribers, verified and following.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReplySettingsWithVerifiedUsers {
    #[serde(rename = "everyone")]
    Everyone,
    #[serde(rename = "mentionedUsers")]
    MentionedUsers,
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "subscribers")]
    Subscribers,
    #[serde(rename = "verified")]
    Verified,
}

