// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvaluateNoteResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<EvaluateNoteResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvaluateNoteResponseData {
    /// Claim opinion model score for the note.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_opinion_score: Option<f64>,
}

