// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldUnauthorizedProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    pub field: String,
    pub resource_type: FieldUnauthorizedProblemResourceType,
    pub section: FieldUnauthorizedProblemSection,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FieldUnauthorizedProblemResourceType {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "tweet")]
    Tweet,
    #[serde(rename = "media")]
    Media,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "space")]
    Space,
}

impl std::fmt::Display for FieldUnauthorizedProblemResourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            FieldUnauthorizedProblemResourceType::User => "user",
            FieldUnauthorizedProblemResourceType::Tweet => "tweet",
            FieldUnauthorizedProblemResourceType::Media => "media",
            FieldUnauthorizedProblemResourceType::List => "list",
            FieldUnauthorizedProblemResourceType::Space => "space",
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FieldUnauthorizedProblemSection {
    #[serde(rename = "data")]
    Data,
    #[serde(rename = "includes")]
    Includes,
}

impl std::fmt::Display for FieldUnauthorizedProblemSection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            FieldUnauthorizedProblemSection::Data => "data",
            FieldUnauthorizedProblemSection::Includes => "includes",
        })
    }
}

