// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A Tweet or error that can be returned by the streaming Tweet API. The values returned with a successful streamed Tweet includes the user provided rules that the Tweet matched.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilteredStreamingTweetResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Tweet>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub includes: Option<Expansions>,
    /// The list of rules which matched the Tweet
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matching_rules: Option<Vec<FilteredStreamingTweetResponseMatchingRulesItem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilteredStreamingTweetResponseMatchingRulesItem {
    pub id: RuleId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<RuleTag>,
}

