// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FoundMediaOrigin {
    /// Unique Identifier of media within provider ( <= 24 characters ))
    pub id: String,
    /// The media provider (e.g., 'giphy') that sourced the media ( <= 8 Characters )
    pub provider: String,
}

