// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Geo {
    pub bbox: Vec<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geometry: Option<Point>,
    pub properties: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "type")]
    pub type_: GeoType,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GeoType {
    #[serde(rename = "Feature")]
    Feature,
}

impl std::fmt::Display for GeoType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            GeoType::Feature => "Feature",
        })
    }
}

