// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeoRestrictions {
    GeoRestrictionsVariant0(GeoRestrictionsVariant0),
    GeoRestrictionsVariant1(GeoRestrictionsVariant1),
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeoRestrictionsVariant0 {
    /// List of blacklisted country codes
    pub blacklisted_country_codes: Vec<String>,
    /// List of whitelisted country codes
    pub whitelisted_country_codes: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeoRestrictionsVariant1 {
    /// List of blacklisted country codes
    pub blacklisted_country_codes: Vec<String>,
    /// List of whitelisted country codes
    pub whitelisted_country_codes: Vec<String>,
}

