// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Get2SpacesSearchResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<Space>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub includes: Option<Expansions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meta: Option<Get2SpacesSearchResponseMeta>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Get2SpacesSearchResponseMeta {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_count: Option<ResultCount>,
}

