// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashtagFields {
    /// The text of the Hashtag.
    pub tag: String,
}

