// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvalidRequestProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<InvalidRequestProblemErrorsItem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvalidRequestProblemErrorsItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, Vec<String>>>,
}

