// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KillConnectionsByEndpointResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<KillConnectionsByEndpointResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KillConnectionsByEndpointResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_kills: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<KillConnectionsByEndpointResponseDataResultsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub successful_kills: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KillConnectionsByEndpointResponseDataResultsItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

