// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A response from getting a media upload request status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<MediaUploadResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadResponseData {
    /// Number of seconds after which upload session expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_after_secs: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<MediaId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_key: Option<MediaKey>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processing_info: Option<ProcessingInfo>,
    /// Size of the upload
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

