// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaTimestampedMetrics {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics: Option<MediaMetrics>,
    /// ISO8601 Time
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

