// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A response from getting a media upload request status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadAppendResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<MediaUploadAppendResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadAppendResponseData {
    /// Unix epoch time in seconds after when the upload session expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,
}

