// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadRequestOneShot {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_owners: Option<Vec<UserId>>,
    pub media: MediaUploadRequestOneShotMedia,
    pub media_category: MediaCategoryOneShot,
    /// The type of image or subtitle.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_type: Option<MediaUploadRequestOneShotMediaType>,
    /// Whether this media is shared or not.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MediaUploadRequestOneShotMedia {
    MediaPayloadBinary(MediaPayloadBinary),
    MediaPayloadByte(MediaPayloadByte),
}

/// The type of image or subtitle.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaUploadRequestOneShotMediaType {
    #[serde(rename = "text/srt")]
    TextSrt,
    #[serde(rename = "text/vtt")]
    TextVtt,
    #[serde(rename = "image/jpeg")]
    ImageJpeg,
    #[serde(rename = "image/bmp")]
    ImageBmp,
    #[serde(rename = "image/png")]
    ImagePng,
    #[serde(rename = "image/webp")]
    ImageWebp,
    #[serde(rename = "image/pjpeg")]
    ImagePjpeg,
    #[serde(rename = "image/tiff")]
    ImageTiff,
}

