// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaUploadConfigRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_owners: Option<Vec<UserId>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_category: Option<MediaCategory>,
    /// The type of media.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_type: Option<MediaUploadConfigRequestMediaType>,
    /// Whether this media is shared or not.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,
    /// The total size of the media upload in bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<i32>,
}


/// The type of media.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MediaUploadConfigRequestMediaType {
    #[serde(rename = "video/mp4")]
    VideoMp4,
    #[serde(rename = "video/webm")]
    VideoWebm,
    #[serde(rename = "video/mp2t")]
    VideoMp2t,
    #[serde(rename = "video/quicktime")]
    VideoQuicktime,
    #[serde(rename = "text/srt")]
    TextSrt,
    #[serde(rename = "text/vtt")]
    TextVtt,
    #[serde(rename = "image/jpeg")]
    ImageJpeg,
    #[serde(rename = "image/gif")]
    ImageGif,
    #[serde(rename = "image/bmp")]
    ImageBmp,
    #[serde(rename = "image/png")]
    ImagePng,
    #[serde(rename = "image/webp")]
    ImageWebp,
    #[serde(rename = "image/pjpeg")]
    ImagePjpeg,
    #[serde(rename = "image/tiff")]
    ImageTiff,
    #[serde(rename = "model/gltf-binary")]
    ModelGltfBinary,
    #[serde(rename = "model/vnd.usdz+zip")]
    ModelVndUsdzZip,
}

