// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaAnalytics {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<MediaAnalyticsDataItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MediaAnalyticsDataItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_key: Option<MediaKey>,
    /// Array containing metrics data along with the timestamps of their recording.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamped_metrics: Option<Vec<MediaTimestampedMetrics>>,
}

