// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetadataCreateRequest {
    pub id: MediaId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<MetadataCreateRequestMetadata>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetadataCreateRequestMetadata {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allow_download_status: Option<AllowDownloadStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alt_text: Option<AltText>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audience_policy: Option<AudiencePolicy>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_expiration: Option<ContentExpiration>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain_restrictions: Option<DomainRestrictions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub found_media_origin: Option<FoundMediaOrigin>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_restrictions: Option<GeoRestrictions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub management_info: Option<ManagementInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_image: Option<PreviewImage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sensitive_media_warning: Option<SensitiveMediaWarning>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shared_info: Option<SharedInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sticker_info: Option<StickerInfo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_source: Option<UploadSource>,
}

