// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MuteUserMutationResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<MuteUserMutationResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MuteUserMutationResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub muting: Option<bool>,
}

