// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// An AI generated news story.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct News {
    /// The news category.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cluster_posts_results: Option<Vec<NewsClusterPostsResultsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<NewsContexts>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disclaimer: Option<String>,
    /// The news hook.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hook: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_updated_at_ms: Option<chrono::DateTime<chrono::Utc>>,
    /// The headline.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub rest_id: NewsId,
    /// The news summary.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewsClusterPostsResultsItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post_id: Option<TweetId>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewsContexts {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entities: Option<NewsContextsEntities>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finance: Option<NewsContextsFinance>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sports: Option<NewsContextsSports>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewsContextsEntities {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organizations: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub people: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub places: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewsContextsFinance {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tickers: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewsContextsSports {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<String>>,
}

