// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// The scoring status of a Community Note.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteScoringStatus {
    /// Whether the user has access to the scoring status of the Community Note.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_access: Option<bool>,
    /// Rating count stats per model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating_counts_per_model: Option<NoteScoringStatusRatingCountsPerModel>,
}


/// Rating count stats per model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteScoringStatusRatingCountsPerModel {
    /// The name of the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<NoteRatingCountsPerModel>,
}

