// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Rating counts for a rater factor bucket.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteFactorBucketCounts {
    /// The count of helpful ratings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub helpful_count: Option<i32>,
    /// Helpful tag counts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub helpful_tag_counts: Option<NoteFactorBucketCountsHelpfulTagCounts>,
    /// The count of not helpful ratings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not_helpful_count: Option<i32>,
    /// Not helpful tag counts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not_helpful_tag_counts: Option<NoteFactorBucketCountsNotHelpfulTagCounts>,
    /// The count of somewhat helpful ratings.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub somewhat_helpful_count: Option<i32>,
}


/// Helpful tag counts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteFactorBucketCountsHelpfulTagCounts {
    /// The count of the tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_count: Option<i32>,
    /// The name of the tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
}

/// Not helpful tag counts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteFactorBucketCountsNotHelpfulTagCounts {
    /// The count of the tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_count: Option<i32>,
    /// The name of the tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
}

