// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A X Community Note is a note on a Post.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteInfo {
    pub classification: NoteClassification,
    /// Whether the note is a media note.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_media_note: Option<bool>,
    pub misleading_tags: Vec<MisleadingTags>,
    /// The text summary in the Community Note.
    pub text: String,
    /// Whether the note provided trustworthy links.
    pub trustworthy_sources: bool,
}

