// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A X Community Note is a note on a Post.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Note {
    pub id: NoteId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub info: Option<NoteInfo>,
    pub post_id: TweetId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scoring_status: Option<NoteScoringStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<NoteRatingStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub test_result: Option<NoteTestResult>,
}

