// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// The rating counts of a Community Note per model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteRatingCountsPerModel {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub negative_factor_bucket_counts: Option<NoteFactorBucketCounts>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub neutral_factor_bucket_counts: Option<NoteFactorBucketCounts>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub positive_factor_bucket_counts: Option<NoteFactorBucketCounts>,
}

