// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationalDisconnectProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disconnect_type: Option<OperationalDisconnectProblemDisconnectType>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OperationalDisconnectProblemDisconnectType {
    #[serde(rename = "OperationalDisconnect")]
    OperationalDisconnect,
    #[serde(rename = "UpstreamOperationalDisconnect")]
    UpstreamOperationalDisconnect,
    #[serde(rename = "ForceDisconnect")]
    ForceDisconnect,
    #[serde(rename = "UpstreamUncleanDisconnect")]
    UpstreamUncleanDisconnect,
    #[serde(rename = "SlowReader")]
    SlowReader,
    #[serde(rename = "InternalError")]
    InternalError,
    #[serde(rename = "ClientApplicationStateDegraded")]
    ClientApplicationStateDegraded,
    #[serde(rename = "InvalidRules")]
    InvalidRules,
}

impl std::fmt::Display for OperationalDisconnectProblemDisconnectType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            OperationalDisconnectProblemDisconnectType::OperationalDisconnect => "OperationalDisconnect",
            OperationalDisconnectProblemDisconnectType::UpstreamOperationalDisconnect => "UpstreamOperationalDisconnect",
            OperationalDisconnectProblemDisconnectType::ForceDisconnect => "ForceDisconnect",
            OperationalDisconnectProblemDisconnectType::UpstreamUncleanDisconnect => "UpstreamUncleanDisconnect",
            OperationalDisconnectProblemDisconnectType::SlowReader => "SlowReader",
            OperationalDisconnectProblemDisconnectType::InternalError => "InternalError",
            OperationalDisconnectProblemDisconnectType::ClientApplicationStateDegraded => "ClientApplicationStateDegraded",
            OperationalDisconnectProblemDisconnectType::InvalidRules => "InvalidRules",
        })
    }
}

