// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Place {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contained_within: Option<Vec<PlaceId>>,
    /// The full name of the county in which this place exists.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country_code: Option<CountryCode>,
    /// The full name of this place.
    pub full_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<Geo>,
    pub id: PlaceId,
    /// The human readable name of this place.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub place_type: Option<PlaceType>,
}

