// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Contact information associated with a Plaid account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidAccountContact {
    /// List of addresses associated with the account holder.
    pub addresses: Vec<PlaidAddress>,
    /// List of email addresses associated with the account holder.
    pub emails: Vec<String>,
    pub name: PlaidName,
    /// Relationship of the contact to the account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub relationship: Option<String>,
    /// List of telephone numbers associated with the account holder.
    pub telephones: Vec<PlaidTelephone>,
}

