// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Descriptor for a Plaid account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidAccount {
    /// The category of the account (e.g., personal, business).
    #[serde(rename = "accountCategory")]
    pub account_category: String,
    /// The Plaid account ID.
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// The last 2-4 digits of the account number.
    #[serde(rename = "accountNumberDisplay")]
    pub account_number_display: String,
    /// The type of the account (e.g., checking, savings).
    #[serde(rename = "accountType")]
    pub account_type: String,
    /// The available balance of the account.
    #[serde(rename = "availableBalance", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<f64>,
    pub currency: PlaidCurrency,
    /// The current balance of the account.
    #[serde(rename = "currentBalance", skip_serializing_if = "Option::is_none")]
    pub current_balance: Option<f64>,
    /// The nickname of the account.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    /// The name of the product associated with the account.
    #[serde(rename = "productName")]
    pub product_name: String,
    /// The status of the account.
    pub status: String,
}

