// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Telephone information for the account holder.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidTelephone {
    /// The country code for the phone number (e.g., '+1').
    pub country: String,
    /// The phone number.
    pub number: String,
    /// The type of phone number (e.g., 'mobile').
    #[serde(rename = "type")]
    pub type_: String,
}

