// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Descriptor for a Plaid account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidAccountTransaction {
    /// The category of the account (e.g., personal, business).
    #[serde(rename = "accountCategory")]
    pub account_category: String,
    /// The amount transacted.
    pub amount: f64,
    /// Memo for transaction (e.g. CREDIT)
    #[serde(rename = "debitCreditMemo")]
    pub debit_credit_memo: String,
    /// The transaction description
    pub description: String,
    /// The timestamp when the transaction was posted.
    #[serde(rename = "postedTimestamp", skip_serializing_if = "Option::is_none")]
    pub posted_timestamp: Option<String>,
    /// The status of the transaction.
    pub status: String,
    /// The identifier for the transaction.
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    /// The timestamp when the transaction occurred.
    #[serde(rename = "transactionTimestamp")]
    pub transaction_timestamp: String,
}

