// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Name information for the account holder.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidName {
    /// The first name of the account holder.
    pub first: String,
    /// The last name of the account holder.
    pub last: String,
}

