// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Payment network details associated with the account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaidAccountPaymentNetwork {
    /// The bank ID associated with the account.
    #[serde(rename = "bankId")]
    pub bank_id: String,
    /// The payment network identifier.
    pub identifier: String,
    /// Indicates if transfers into the account are supported.
    #[serde(rename = "transferIn")]
    pub transfer_in: bool,
    /// Indicates if transfers out of the account are supported.
    #[serde(rename = "transferOut")]
    pub transfer_out: bool,
    /// The type of payment network (e.g., ACH, SEPA).
    #[serde(rename = "type")]
    pub type_: String,
}

