// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represent a Poll attached to a Tweet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Poll {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_datetime: Option<chrono::DateTime<chrono::Utc>>,
    pub id: PollId,
    pub options: Vec<PollOption>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voting_status: Option<PollVotingStatus>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PollVotingStatus {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "closed")]
    Closed,
}

