// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessingInfo {
    /// Number of seconds to check again for status
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check_after_secs: Option<i32>,
    /// Percent of upload progress
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress_percent: Option<i32>,
    /// State of upload
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<ProcessingInfoState>,
}


/// State of upload
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProcessingInfoState {
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "failed")]
    Failed,
}

