// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Public key information for Chat encryption
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicKey {
    /// Identity public key (base64 encoded).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    /// Signing public key (base64 encoded).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signing_public_key: Option<String>,
    /// Juicebox configuration.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_map: Option<PublicKeyTokenMap>,
    /// Public key version.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}


/// Juicebox configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicKeyTokenMap {
    /// Raw JSON for Juicebox SDK.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_store_token_map_json: Option<String>,
    /// Maximum guess count for Juicebox.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_guess_count: Option<i32>,
    /// List of Juicebox realms.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub realms: Option<Vec<PublicKeyTokenMapRealmsItem>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicKeyTokenMapRealmsItem {
    /// Realm URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Realm identifier.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub realm_id: Option<String>,
    /// JWT auth token for realm.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

