// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Confirmation that the replay job request was accepted.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplayJobCreateResponse {
    /// The UTC timestamp indicating when the replay job was created.
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// The unique identifier for the initiated replay job.
    pub job_id: String,
}

