// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceUnavailableProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    pub parameter: String,
    pub resource_id: String,
    pub resource_type: ResourceUnavailableProblemResourceType,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ResourceUnavailableProblemResourceType {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "tweet")]
    Tweet,
    #[serde(rename = "media")]
    Media,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "space")]
    Space,
}

