// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A user-provided stream filtering rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Rule {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<RuleId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<RuleTag>,
    pub value: RuleValue,
}

