// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesResponseMetadata {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<NextToken>,
    /// Number of Rules in result set.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result_count: Option<i32>,
    pub sent: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<RulesRequestSummary>,
}

