// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RulesRequestSummary {
    RulesRequestSummaryVariant0(RulesRequestSummaryVariant0),
    RulesRequestSummaryVariant1(RulesRequestSummaryVariant1),
}


/// A summary of the results of the addition of user-specified stream filtering rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesRequestSummaryVariant0 {
    /// Number of user-specified stream filtering rules that were created.
    pub created: i32,
    /// Number of invalid user-specified stream filtering rules.
    pub invalid: i32,
    /// Number of user-specified stream filtering rules that were not created.
    pub not_created: i32,
    /// Number of valid user-specified stream filtering rules.
    pub valid: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesRequestSummaryVariant1 {
    /// Number of user-specified stream filtering rules that were deleted.
    pub deleted: i32,
    /// Number of user-specified stream filtering rules that were not deleted.
    pub not_deleted: i32,
}

