// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represent a Search Count Result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchCount {
    pub end: End,
    pub start: Start,
    pub tweet_count: TweetCount,
}

