// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Space {
    /// Creation time of the Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<UserId>,
    /// End time of the Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<chrono::DateTime<chrono::Utc>>,
    /// The user ids for the hosts of the Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host_ids: Option<Vec<UserId>>,
    pub id: SpaceId,
    /// An array of user ids for people who were invited to a Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invited_user_ids: Option<Vec<UserId>>,
    /// Denotes if the Space is a ticketed Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_ticketed: Option<bool>,
    /// The language of the Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    /// The number of participants in a Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participant_count: Option<i32>,
    /// A date time stamp for when a Space is scheduled to begin.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_start: Option<chrono::DateTime<chrono::Utc>>,
    /// An array of user ids for people who were speakers in a Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub speaker_ids: Option<Vec<UserId>>,
    /// When the Space was started as a date string.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    /// The current state of the Space.
    pub state: SpaceState,
    /// The number of people who have either purchased a ticket or set a reminder for this Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    /// The title of the Space.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The topics of a Space, as selected by its creator.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<SpaceTopicsItem>>,
    /// When the Space was last updated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}


/// The current state of the Space.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SpaceState {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "ended")]
    Ended,
}

impl std::fmt::Display for SpaceState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            SpaceState::Live => "live",
            SpaceState::Scheduled => "scheduled",
            SpaceState::Ended => "ended",
        })
    }
}

/// The X Topic object.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpaceTopicsItem {
    /// The description of the given topic.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// An ID suitable for use in the REST API.
    pub id: String,
    /// The name of the given topic.
    pub name: String,
}

