// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Sticker {
    /// width-to-height ratio of the media
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<f64>,
    /// A unique identifier for the group of annotations associated with the media
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_annotation_id: Option<f64>,
    /// Unique identifier for sticker
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A unique identifier for the sticker set associated with the media
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sticker_set_annotation_id: Option<f64>,
    /// Scale or rotate the media on the x-axis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_a: Option<f64>,
    /// Skew the media on the x-axis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_b: Option<f64>,
    /// Skew the media on the y-axis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_c: Option<f64>,
    /// Scale or rotate the media on the y-axis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_d: Option<f64>,
    /// Scale or rotate the media on the x-axis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_tx: Option<f64>,
    /// The vertical translation (shift) value for the media
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transform_ty: Option<f64>,
}

