// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionsListGetResponse {
    /// The list of active subscriptions for a specified webhook
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<SubscriptionsListGetResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


/// The list of active subscriptions for a specified webhook
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionsListGetResponseData {
    /// The application ID
    pub application_id: String,
    /// List of active subscriptions for the webhook
    pub subscriptions: Vec<SubscriptionsListGetResponseDataSubscriptionsItem>,
    /// The associated webhook ID
    pub webhook_id: String,
    /// The url for the associated webhook
    pub webhook_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionsListGetResponseDataSubscriptionsItem {
    /// The ID of the user the webhook is subscribed to
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

