// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionsCountGetResponse {
    /// The count of active subscriptions across all webhooks
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<SubscriptionsCountGetResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


/// The count of active subscriptions across all webhooks
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionsCountGetResponseData {
    /// The account name
    pub account_name: String,
    /// The limit for subscriptions for this app
    pub provisioned_count: String,
    /// The number of active subscriptions across all webhooks
    pub subscriptions_count_all: String,
    /// The number of active direct message subscriptions
    pub subscriptions_count_direct_messages: String,
}

