// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubtitlesDeleteRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<MediaId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language_code: Option<SubtitleLanguageCode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_category: Option<MediaCategorySubtitles>,
}

