// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// The topic of a Space, as selected by its creator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Topic {
    /// The description of the given topic.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub id: TopicId,
    /// The name of the given topic.
    pub name: String,
}

