// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A trend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trend {
    /// Name of the trend.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trend_name: Option<String>,
    /// Number of Posts in this trend.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tweet_count: Option<i32>,
}

