// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TweetLabelStreamResponse {
    TweetLabelStreamResponseVariant0(TweetLabelStreamResponseVariant0),
    TweetLabelStreamResponseVariant1(TweetLabelStreamResponseVariant1),
}


/// Tweet Label event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetLabelStreamResponseVariant0 {
    pub data: TweetLabelData,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetLabelStreamResponseVariant1 {
    pub errors: Vec<Problem>,
}

