// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetUnviewable {
    /// If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
    pub application: String,
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    pub tweet: TweetUnviewableTweet,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetUnviewableTweet {
    pub author_id: UserId,
    pub id: TweetId,
}

