// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TweetComplianceData {
    TweetDeleteComplianceSchema(TweetDeleteComplianceSchema),
    TweetWithheldComplianceSchema(TweetWithheldComplianceSchema),
    TweetDropComplianceSchema(TweetDropComplianceSchema),
    TweetUndropComplianceSchema(TweetUndropComplianceSchema),
    TweetEditComplianceSchema(TweetEditComplianceSchema),
}

