// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetHideResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<TweetHideResponseData>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetHideResponseData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
}

