// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetEditComplianceObjectSchema {
    pub edit_tweet_ids: Vec<TweetId>,
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    pub initial_tweet_id: TweetId,
    pub tweet: TweetEditComplianceObjectSchemaTweet,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetEditComplianceObjectSchemaTweet {
    pub id: TweetId,
}

