// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetNotice {
    /// If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
    pub application: String,
    /// Information shown on the Tweet label
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    /// The type of label on the Tweet
    pub event_type: String,
    /// Link to more information about this kind of label
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extended_details_url: Option<String>,
    /// Title/header of the Tweet label
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label_title: Option<String>,
    pub tweet: TweetNoticeTweet,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetNoticeTweet {
    pub author_id: UserId,
    pub id: TweetId,
}

