// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetWithheld {
    /// Indicates if the content is being withheld for on the basis of copyright infringement.
    pub copyright: bool,
    /// Provides a list of countries where this content is not available.
    pub country_codes: Vec<CountryCode>,
    /// Indicates whether the content being withheld is the `tweet` or a `user`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<TweetWithheldScope>,
}


/// Indicates whether the content being withheld is the `tweet` or a `user`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetWithheldScope {
    #[serde(rename = "tweet")]
    Tweet,
    #[serde(rename = "user")]
    User,
}

impl std::fmt::Display for TweetWithheldScope {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            TweetWithheldScope::Tweet => "tweet",
            TweetWithheldScope::User => "user",
        })
    }
}

