// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequest {
    /// Card Uri Parameter. This is mutually exclusive from Quote Tweet Id, Poll, Media, and Direct Message Deep Link.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub card_uri: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub community_id: Option<CommunityId>,
    /// Link to take the conversation from the public timeline to a private Direct Message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direct_message_deep_link: Option<String>,
    /// Options for editing an existing Post. When provided, this request will edit the specified Post instead of creating a new one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edit_options: Option<TweetCreateRequestEditOptions>,
    /// Exclusive Tweet for super followers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub for_super_followers_only: Option<bool>,
    /// Place ID being attached to the Tweet for geo location.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<TweetCreateRequestGeo>,
    /// Whether this Post contains AI-generated media. When true, the Post will be labeled accordingly.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub made_with_ai: Option<bool>,
    /// Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media: Option<TweetCreateRequestMedia>,
    /// Nullcasted (promoted-only) Posts do not appear in the public timeline and are not served to followers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nullcast: Option<bool>,
    /// Whether this Post is a paid partnership. When true, the Post will be labeled as a paid promotion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_partnership: Option<bool>,
    /// Poll options for a Tweet with a poll. This is mutually exclusive from Media, Quote Tweet Id, and Card URI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub poll: Option<TweetCreateRequestPoll>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quote_tweet_id: Option<TweetId>,
    /// Tweet information of the Tweet being replied to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply: Option<TweetCreateRequestReply>,
    /// Settings to indicate who can reply to the Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_settings: Option<TweetCreateRequestReplySettings>,
    /// Share community post with followers too.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub share_with_followers: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<TweetText>,
}


/// Options for editing an existing Post. When provided, this request will edit the specified Post instead of creating a new one.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestEditOptions {
    pub previous_post_id: TweetId,
}

/// Place ID being attached to the Tweet for geo location.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestGeo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub place_id: Option<String>,
}

/// Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestMedia {
    /// Call-to-action button rendered on the media entity. Exactly one variant should be set.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub call_to_actions: Option<TweetCreateRequestMediaCallToActions>,
    /// Description for the media. Rendered on the Post card for video and Amplify content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// When true, the media's asset URLs do not expire and external syndicated playback is allowed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embeddable: Option<bool>,
    /// A list of Media Ids to be attached to a created Tweet.
    pub media_ids: Vec<MediaId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_media_id: Option<MediaId>,
    /// A list of User Ids to be tagged in the media for created Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tagged_user_ids: Option<Vec<UserId>>,
    /// Title for the media. Rendered on the Post card for video and Amplify content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// Poll options for a Tweet with a poll. This is mutually exclusive from Media, Quote Tweet Id, and Card URI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestPoll {
    /// Duration of the poll in minutes.
    pub duration_minutes: i32,
    pub options: Vec<String>,
    /// Settings to indicate who can reply to the Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_settings: Option<TweetCreateRequestPollReplySettings>,
}

/// Tweet information of the Tweet being replied to.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestReply {
    /// If set to true, reply metadata will be automatically populated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_populate_reply_metadata: Option<bool>,
    /// A list of User Ids to be excluded from the reply Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclude_reply_user_ids: Option<Vec<UserId>>,
    pub in_reply_to_tweet_id: TweetId,
}

/// Settings to indicate who can reply to the Tweet.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetCreateRequestReplySettings {
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "mentionedUsers")]
    MentionedUsers,
    #[serde(rename = "subscribers")]
    Subscribers,
    #[serde(rename = "verified")]
    Verified,
}

impl std::fmt::Display for TweetCreateRequestReplySettings {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            TweetCreateRequestReplySettings::Following => "following",
            TweetCreateRequestReplySettings::MentionedUsers => "mentionedUsers",
            TweetCreateRequestReplySettings::Subscribers => "subscribers",
            TweetCreateRequestReplySettings::Verified => "verified",
        })
    }
}

/// Call-to-action button rendered on the media entity. Exactly one variant should be set.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestMediaCallToActions {
    /// App Install CTA. At least one store id should be provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_install: Option<TweetCreateRequestMediaCallToActionsAppInstall>,
    /// Visit Site CTA.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visit_site: Option<TweetCreateRequestMediaCallToActionsVisitSite>,
    /// Watch Now CTA.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub watch_now: Option<TweetCreateRequestMediaCallToActionsWatchNow>,
}

/// Settings to indicate who can reply to the Tweet.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetCreateRequestPollReplySettings {
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "mentionedUsers")]
    MentionedUsers,
    #[serde(rename = "subscribers")]
    Subscribers,
    #[serde(rename = "verified")]
    Verified,
}

impl std::fmt::Display for TweetCreateRequestPollReplySettings {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            TweetCreateRequestPollReplySettings::Following => "following",
            TweetCreateRequestPollReplySettings::MentionedUsers => "mentionedUsers",
            TweetCreateRequestPollReplySettings::Subscribers => "subscribers",
            TweetCreateRequestPollReplySettings::Verified => "verified",
        })
    }
}

/// App Install CTA. At least one store id should be provided.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestMediaCallToActionsAppInstall {
    /// Apple App Store iPhone app id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app_store_id: Option<String>,
    /// Apple App Store iPad app id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ipad_app_store_id: Option<String>,
    /// Google Play Store app id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub play_store_id: Option<String>,
}

/// Visit Site CTA.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestMediaCallToActionsVisitSite {
    /// HTTPS URL the CTA links to.
    pub url: String,
}

/// Watch Now CTA.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetCreateRequestMediaCallToActionsWatchNow {
    /// HTTPS URL the CTA links to.
    pub url: String,
}

