// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tweet {
    /// Specifies the type of attachments (if any) present in this Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<TweetAttachments>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_id: Option<UserId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub community_id: Option<CommunityId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_annotations: Option<Vec<ContextAnnotation>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<TweetId>,
    /// Creation time of the Tweet.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_text_range: Option<DisplayTextRange>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edit_controls: Option<TweetEditControls>,
    /// A list of Tweet Ids in this Tweet chain.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edit_history_tweet_ids: Option<Vec<TweetId>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entities: Option<FullTextEntities>,
    /// The location tagged on the Tweet, if the user provided one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<TweetGeo>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<TweetId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_reply_to_user_id: Option<UserId>,
    /// Language of the Tweet, if detected by X. Returned as a BCP47 language tag.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    /// The matched media notes for the post.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matched_media_notes: Option<TweetMatchedMediaNotes>,
    /// Nonpublic engagement metrics for the Tweet at the time of the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub non_public_metrics: Option<TweetNonPublicMetrics>,
    /// The full-content of the Tweet, including text beyond 280 characters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note_tweet: Option<TweetNoteTweet>,
    /// Organic nonpublic engagement metrics for the Tweet at the time of the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organic_metrics: Option<TweetOrganicMetrics>,
    /// Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub possibly_sensitive: Option<bool>,
    /// Promoted nonpublic engagement metrics for the Tweet at the time of the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promoted_metrics: Option<TweetPromotedMetrics>,
    /// Engagement metrics for the Tweet at the time of the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_metrics: Option<TweetPublicMetrics>,
    /// A list of Posts this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub referenced_tweets: Option<Vec<TweetReferencedTweetsItem>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_settings: Option<ReplySettingsWithVerifiedUsers>,
    /// The scopes for this tweet
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scopes: Option<TweetScopes>,
    /// This is deprecated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggested_source_links: Option<Vec<UrlEntity>>,
    /// Suggested source links and the number of requests that included each link.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggested_source_links_with_counts: Option<TweetSuggestedSourceLinksWithCounts>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<TweetText>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<UserName>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub withheld: Option<TweetWithheld>,
}


/// Specifies the type of attachments (if any) present in this Tweet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetAttachments {
    /// A list of Media Keys for each one of the media attachments (if media are attached).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_keys: Option<Vec<MediaKey>>,
    /// A list of Posts the media on this Tweet was originally posted in. For example, if the media on a tweet is re-used in another Tweet, this refers to the original, source Tweet..
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_source_tweet_id: Option<Vec<TweetId>>,
    /// A list of poll IDs (if polls are attached).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub poll_ids: Option<Vec<PollId>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetEditControls {
    /// Time when Tweet is no longer editable.
    pub editable_until: chrono::DateTime<chrono::Utc>,
    /// Number of times this Tweet can be edited.
    pub edits_remaining: i32,
    /// Indicates if this Tweet is eligible to be edited.
    pub is_edit_eligible: bool,
}

/// The location tagged on the Tweet, if the user provided one.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetGeo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coordinates: Option<Point>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub place_id: Option<PlaceId>,
}

/// The matched media notes for the post.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetMatchedMediaNotes {
    /// The status of the media note match.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub match_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note_id: Option<NoteId>,
}

/// Nonpublic engagement metrics for the Tweet at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetNonPublicMetrics {
    /// Number of times this Tweet has been viewed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub impression_count: Option<i32>,
}

/// The full-content of the Tweet, including text beyond 280 characters.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetNoteTweet {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entities: Option<TweetNoteTweetEntities>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<NoteTweetText>,
}

/// Organic nonpublic engagement metrics for the Tweet at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetOrganicMetrics {
    /// Number of times this Tweet has been viewed.
    pub impression_count: i32,
    /// Number of times this Tweet has been liked.
    pub like_count: i32,
    /// Number of times this Tweet has been replied to.
    pub reply_count: i32,
    /// Number of times this Tweet has been Retweeted.
    pub retweet_count: i32,
}

/// Promoted nonpublic engagement metrics for the Tweet at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetPromotedMetrics {
    /// Number of times this Tweet has been viewed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub impression_count: Option<i32>,
    /// Number of times this Tweet has been liked.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i32>,
    /// Number of times this Tweet has been replied to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_count: Option<i32>,
    /// Number of times this Tweet has been Retweeted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retweet_count: Option<i32>,
}

/// Engagement metrics for the Tweet at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetPublicMetrics {
    /// Number of times this Tweet has been bookmarked.
    pub bookmark_count: i32,
    /// Number of times this Tweet has been viewed.
    pub impression_count: i32,
    /// Number of times this Tweet has been liked.
    pub like_count: i32,
    /// Number of times this Tweet has been quoted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quote_count: Option<i32>,
    /// Number of times this Tweet has been replied to.
    pub reply_count: i32,
    /// Number of times this Tweet has been Retweeted.
    pub retweet_count: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetReferencedTweetsItem {
    pub id: TweetId,
    #[serde(rename = "type")]
    pub type_: TweetReferencedTweetsItemType,
}

/// The scopes for this tweet
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetScopes {
    /// Indicates if this Tweet is viewable by followers without the Tweet ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub followers: Option<bool>,
}

/// Suggested source links and the number of requests that included each link.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetSuggestedSourceLinksWithCounts {
    /// Number of note requests that included the source link.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<UrlEntity>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetNoteTweetEntities {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cashtags: Option<Vec<CashtagEntity>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hashtags: Option<Vec<HashtagEntity>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<MentionEntity>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<UrlEntity>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TweetReferencedTweetsItemType {
    #[serde(rename = "retweeted")]
    Retweeted,
    #[serde(rename = "quoted")]
    Quoted,
    #[serde(rename = "replied_to")]
    RepliedTo,
}

