// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TweetComplianceStreamResponse {
    TweetComplianceStreamResponseVariant0(TweetComplianceStreamResponseVariant0),
    TweetComplianceStreamResponseVariant1(TweetComplianceStreamResponseVariant1),
}


/// Compliance event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetComplianceStreamResponseVariant0 {
    pub data: TweetComplianceData,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetComplianceStreamResponseVariant1 {
    pub errors: Vec<Problem>,
}

