// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetComplianceSchema {
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quote_tweet_id: Option<TweetId>,
    pub tweet: TweetComplianceSchemaTweet,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TweetComplianceSchemaTweet {
    pub author_id: UserId,
    pub id: TweetId,
}

