// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represent the information for the URL image.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UrlImage {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<MediaHeight>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<Url>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<MediaWidth>,
}

