// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represent the portion of text recognized as a URL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UrlFields {
    /// Description of the URL landing page.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The URL as displayed in the X client.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expanded_url: Option<Url>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<UrlImage>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_key: Option<MediaKey>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<HttpStatusCode>,
    /// Title of the page the URL points to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Fully resolved url.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unwound_url: Option<url::Url>,
    pub url: Url,
}

