// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageCapExceededProblem {
    #[serde(flatten)]
    pub flatten_0: Problem,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<UsageCapExceededProblemPeriod>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<UsageCapExceededProblemScope>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UsageCapExceededProblemPeriod {
    #[serde(rename = "Daily")]
    Daily,
    #[serde(rename = "Monthly")]
    Monthly,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UsageCapExceededProblemScope {
    #[serde(rename = "Account")]
    Account,
    #[serde(rename = "Product")]
    Product,
}

