// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Usage per client app
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Number of days left for the Tweet cap to reset
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cap_reset_day: Option<i32>,
    /// The daily usage breakdown for each Client Application a project
    #[serde(skip_serializing_if = "Option::is_none")]
    pub daily_client_app_usage: Option<Vec<ClientAppUsage>>,
    /// The daily usage breakdown for a project
    #[serde(skip_serializing_if = "Option::is_none")]
    pub daily_project_usage: Option<UsageDailyProjectUsage>,
    /// Total number of Posts that can be read in this project per month
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_cap: Option<i32>,
    /// The unique identifier for this project
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// The number of Posts read in this project
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_usage: Option<i32>,
}


/// The daily usage breakdown for a project
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageDailyProjectUsage {
    /// The unique identifier for this project
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    /// The usage value
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<UsageFields>>,
}

