// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Represents the data for Usage
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageFields {
    /// The time period for the usage
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<chrono::DateTime<chrono::Utc>>,
    /// The usage value
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<i32>,
}

