// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// The X User object.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// Metadata about a user's affiliation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub affiliation: Option<UserAffiliation>,
    /// Returns detailed information about the relationship between two users.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub connection_status: Option<Vec<UserConnectionStatusItem>>,
    /// Creation time of this User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    /// The text of this User's profile description (also known as bio), if the User provided one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of metadata found in the User's profile description.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entities: Option<UserEntities>,
    pub id: UserId,
    /// The location specified in the User's profile, if the User provided one. As this is a freeform value, it may not indicate a valid location, but it may be fuzzily evaluated when performing searches with location queries.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub most_recent_tweet_id: Option<TweetId>,
    /// The friendly name of this User, as shown on their profile.
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pinned_tweet_id: Option<TweetId>,
    /// The URL to the profile banner for this User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_banner_url: Option<url::Url>,
    /// The URL to the profile image for this User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_image_url: Option<url::Url>,
    /// Indicates if this User has chosen to protect their Posts (in other words, if this User's Posts are private).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protected: Option<bool>,
    /// A list of metrics for this User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_metrics: Option<UserPublicMetrics>,
    /// Indicates if you can send a DM to this User
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receives_your_dm: Option<bool>,
    /// The X Blue subscription type of the user, eg: Basic, Premium, PremiumPlus or None.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_type: Option<UserSubscriptionType>,
    /// The URL specified in the User's profile.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    pub username: UserName,
    /// Indicate if this User is a verified X User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    /// The X Blue verified type of the user, eg: blue, government, business or none.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_type: Option<UserVerifiedType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub withheld: Option<UserWithheld>,
}


/// Metadata about a user's affiliation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserAffiliation {
    /// The badge URL corresponding to the affiliation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub badge_url: Option<url::Url>,
    /// The description of the affiliation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The URL, if available, to details about an affiliation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<url::Url>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Vec<UserId>>,
}

/// Type of connection between users.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserConnectionStatusItem {
    #[serde(rename = "follow_request_received")]
    FollowRequestReceived,
    #[serde(rename = "follow_request_sent")]
    FollowRequestSent,
    #[serde(rename = "blocking")]
    Blocking,
    #[serde(rename = "followed_by")]
    FollowedBy,
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "muting")]
    Muting,
}

impl std::fmt::Display for UserConnectionStatusItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UserConnectionStatusItem::FollowRequestReceived => "follow_request_received",
            UserConnectionStatusItem::FollowRequestSent => "follow_request_sent",
            UserConnectionStatusItem::Blocking => "blocking",
            UserConnectionStatusItem::FollowedBy => "followed_by",
            UserConnectionStatusItem::Following => "following",
            UserConnectionStatusItem::Muting => "muting",
        })
    }
}

/// A list of metadata found in the User's profile description.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserEntities {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<FullTextEntities>,
    /// Expanded details for the URL specified in the User's profile, with start and end indices.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<UserEntitiesUrl>,
}

/// A list of metrics for this User.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserPublicMetrics {
    /// Number of Users who are following this User.
    pub followers_count: i32,
    /// Number of Users this User is following.
    pub following_count: i32,
    /// The number of likes created by this User.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i32>,
    /// The number of lists that include this User.
    pub listed_count: i32,
    /// The number of Posts (including Retweets) posted by this User.
    pub tweet_count: i32,
}

/// The X Blue subscription type of the user, eg: Basic, Premium, PremiumPlus or None.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserSubscriptionType {
    #[serde(rename = "Basic")]
    Basic,
    #[serde(rename = "Premium")]
    Premium,
    #[serde(rename = "PremiumPlus")]
    PremiumPlus,
    #[serde(rename = "None")]
    None,
}

impl std::fmt::Display for UserSubscriptionType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UserSubscriptionType::Basic => "Basic",
            UserSubscriptionType::Premium => "Premium",
            UserSubscriptionType::PremiumPlus => "PremiumPlus",
            UserSubscriptionType::None => "None",
        })
    }
}

/// The X Blue verified type of the user, eg: blue, government, business or none.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserVerifiedType {
    #[serde(rename = "blue")]
    Blue,
    #[serde(rename = "government")]
    Government,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "none")]
    None,
}

impl std::fmt::Display for UserVerifiedType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            UserVerifiedType::Blue => "blue",
            UserVerifiedType::Government => "government",
            UserVerifiedType::Business => "business",
            UserVerifiedType::None => "none",
        })
    }
}

/// Expanded details for the URL specified in the User's profile, with start and end indices.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserEntitiesUrl {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<UrlEntity>>,
}

