// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileModificationObjectSchema {
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    pub new_value: String,
    pub profile_field: String,
    pub user: UserProfileModificationObjectSchemaUser,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileModificationObjectSchemaUser {
    pub id: UserId,
}

