// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserWithheld {
    /// Provides a list of countries where this content is not available.
    pub country_codes: Vec<CountryCode>,
    /// Indicates that the content being withheld is a `user`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<UserWithheldScope>,
}


/// Indicates that the content being withheld is a `user`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UserWithheldScope {
    #[serde(rename = "user")]
    User,
}

