// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserScrubGeoObjectSchema {
    /// Event time.
    pub event_at: chrono::DateTime<chrono::Utc>,
    pub up_to_tweet_id: TweetId,
    pub user: UserScrubGeoObjectSchemaUser,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserScrubGeoObjectSchemaUser {
    pub id: UserId,
}

