// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Video {
    #[serde(flatten)]
    pub flatten_0: Media,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub non_public_metrics: Option<VideoNonPublicMetrics>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organic_metrics: Option<VideoOrganicMetrics>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_image_url: Option<url::Url>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promoted_metrics: Option<VideoPromotedMetrics>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub public_metrics: Option<VideoPublicMetrics>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variants: Option<Variants>,
}


/// Nonpublic engagement metrics for the Media at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VideoNonPublicMetrics {
    /// Number of users who made it through 0% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_0_count: Option<i32>,
    /// Number of users who made it through 100% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_100_count: Option<i32>,
    /// Number of users who made it through 25% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_25_count: Option<i32>,
    /// Number of users who made it through 50% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_50_count: Option<i32>,
    /// Number of users who made it through 75% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_75_count: Option<i32>,
}

/// Organic nonpublic engagement metrics for the Media at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VideoOrganicMetrics {
    /// Number of users who made it through 0% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_0_count: Option<i32>,
    /// Number of users who made it through 100% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_100_count: Option<i32>,
    /// Number of users who made it through 25% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_25_count: Option<i32>,
    /// Number of users who made it through 50% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_50_count: Option<i32>,
    /// Number of users who made it through 75% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_75_count: Option<i32>,
    /// Number of times this video has been viewed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub view_count: Option<i32>,
}

/// Promoted nonpublic engagement metrics for the Media at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VideoPromotedMetrics {
    /// Number of users who made it through 0% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_0_count: Option<i32>,
    /// Number of users who made it through 100% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_100_count: Option<i32>,
    /// Number of users who made it through 25% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_25_count: Option<i32>,
    /// Number of users who made it through 50% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_50_count: Option<i32>,
    /// Number of users who made it through 75% of the video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub playback_75_count: Option<i32>,
    /// Number of times this video has been viewed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub view_count: Option<i32>,
}

/// Engagement metrics for the Media at the time of the request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VideoPublicMetrics {
    /// Number of times this video has been viewed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub view_count: Option<i32>,
}

