// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookLinksGetResponse {
    /// The list of active webhook links for a given stream
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<WebhookLinksGetResponseData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<Problem>>,
}


/// The list of active webhook links for a given stream
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookLinksGetResponseData {
    /// list of links
    pub links: Vec<WebhookLinksGetResponseDataLinksItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookLinksGetResponseDataLinksItem {
    /// The application ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    /// The user ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub business_user_id: Option<String>,
    /// The datetime the webhook was linked to the stream
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Requested fields to be rendered
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    /// The stream ID associated with the FilteredStream instance
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    /// The unique identifier for the webhook
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<String>,
}

