// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use super::*;

/// A Webhook Configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookConfigCreateResponse {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: WebhookConfigId,
    /// The callback URL of the webhook.
    pub url: String,
    pub valid: bool,
}

