// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! DELETE /2/connections/{endpoint_id} — Terminate connections by endpoint
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub endpoint_id: RequestEndpointId,
}

pub type Response = KillConnectionsByEndpointResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestEndpointId {
    #[serde(rename = "filtered_stream")]
    FilteredStream,
    #[serde(rename = "sample_stream")]
    SampleStream,
    #[serde(rename = "sample10_stream")]
    Sample10Stream,
    #[serde(rename = "firehose_stream")]
    FirehoseStream,
    #[serde(rename = "tweets_compliance_stream")]
    TweetsComplianceStream,
    #[serde(rename = "users_compliance_stream")]
    UsersComplianceStream,
    #[serde(rename = "tweet_label_stream")]
    TweetLabelStream,
    #[serde(rename = "firehose_stream_lang_en")]
    FirehoseStreamLangEn,
    #[serde(rename = "firehose_stream_lang_ja")]
    FirehoseStreamLangJa,
    #[serde(rename = "firehose_stream_lang_ko")]
    FirehoseStreamLangKo,
    #[serde(rename = "firehose_stream_lang_pt")]
    FirehoseStreamLangPt,
    #[serde(rename = "likes_firehose_stream")]
    LikesFirehoseStream,
    #[serde(rename = "likes_sample10_stream")]
    LikesSample10Stream,
    #[serde(rename = "likes_compliance_stream")]
    LikesComplianceStream,
}

impl std::fmt::Display for RequestEndpointId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestEndpointId::FilteredStream => "filtered_stream",
            RequestEndpointId::SampleStream => "sample_stream",
            RequestEndpointId::Sample10Stream => "sample10_stream",
            RequestEndpointId::FirehoseStream => "firehose_stream",
            RequestEndpointId::TweetsComplianceStream => "tweets_compliance_stream",
            RequestEndpointId::UsersComplianceStream => "users_compliance_stream",
            RequestEndpointId::TweetLabelStream => "tweet_label_stream",
            RequestEndpointId::FirehoseStreamLangEn => "firehose_stream_lang_en",
            RequestEndpointId::FirehoseStreamLangJa => "firehose_stream_lang_ja",
            RequestEndpointId::FirehoseStreamLangKo => "firehose_stream_lang_ko",
            RequestEndpointId::FirehoseStreamLangPt => "firehose_stream_lang_pt",
            RequestEndpointId::LikesFirehoseStream => "likes_firehose_stream",
            RequestEndpointId::LikesSample10Stream => "likes_sample10_stream",
            RequestEndpointId::LikesComplianceStream => "likes_compliance_stream",
        })
    }
}

