// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/connections/all.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// DELETE /2/connections/all
pub async fn delete(
    http: &Http,
    _req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = "connections/all";
    http.send::<_, ()>(Method::DELETE, path, None).await
}

