// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! POST /2/tweets/search/webhooks/{webhook_id} — Create stream link
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub webhook_id: WebhookConfigId,
    #[serde(rename = "tweet.fields", skip_serializing_if = "Option::is_none")]
    pub tweet_fields: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expansions: Option<String>,
    #[serde(rename = "media.fields", skip_serializing_if = "Option::is_none")]
    pub media_fields: Option<String>,
    #[serde(rename = "poll.fields", skip_serializing_if = "Option::is_none")]
    pub poll_fields: Option<String>,
    #[serde(rename = "user.fields", skip_serializing_if = "Option::is_none")]
    pub user_fields: Option<String>,
    #[serde(rename = "place.fields", skip_serializing_if = "Option::is_none")]
    pub place_fields: Option<String>,
}

pub type Response = WebhookLinksCreateResponse;

