// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/notes.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// POST /2/notes
pub async fn post(
    http: &Http,
    req: &super::post::Request,
) -> Result<super::post::Response, Error> {
    let path = "notes";
    http.send(Method::POST, path, req.body.as_ref()).await
}

