// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/tweets/counts/recent — Get count of recent Posts
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    pub query: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since_id: Option<TweetId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub until_id: Option<TweetId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_token: Option<PaginationToken36>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pagination_token: Option<PaginationToken36>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub granularity: Option<RequestGranularity>,
    #[serde(rename = "search_count.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub search_count_fields: Option<Vec<crate::x::params::search_count_fields_parameter::SearchCountFields>>,
}

pub type Response = Get2TweetsCountsRecentResponse;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestGranularity {
    #[serde(rename = "minute")]
    Minute,
    #[serde(rename = "hour")]
    Hour,
    #[serde(rename = "day")]
    Day,
}

impl std::fmt::Display for RequestGranularity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            RequestGranularity::Minute => "minute",
            RequestGranularity::Hour => "hour",
            RequestGranularity::Day => "day",
        })
    }
}

