// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/dm_conversations/media/{dm_id}/{media_id}/{resource_id} — Download DM Media
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub dm_id: DmEventId,
    pub media_id: MediaId,
    pub resource_id: DmResourceId,
}

/// 204 No Content / no body / non-JSON response.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Response;

