// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! DELETE /2/dm_events/{event_id} — Delete DM event
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize)]
pub struct Request {
    #[serde(skip_serializing)]
    pub event_id: DmEventId,
}

pub type Response = DeleteDmResponse;

