// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! GET /2/dm_events/{event_id} — Get DM event by ID
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use crate::x::types::*;
#[allow(unused_imports)]
use crate::x::params;
#[allow(unused_imports)]
use crate::x::serde_helpers;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub event_id: DmEventId,
    #[serde(rename = "dm_event.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub dm_event_fields: Option<Vec<crate::x::params::dm_event_fields_parameter::DmEventFields>>,
    #[serde(rename = "expansions", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub expansions: Option<Vec<crate::x::params::dm_event_expansions_parameter::DmEventExpansions>>,
    #[serde(rename = "media.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub media_fields: Option<Vec<crate::x::params::media_fields_parameter::MediaFields>>,
    #[serde(rename = "user.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub user_fields: Option<Vec<crate::x::params::user_fields_parameter::UserFields>>,
    #[serde(rename = "tweet.fields", skip_serializing_if = "Option::is_none", with = "crate::x::serde_helpers::csv_vec_opt")]
    pub tweet_fields: Option<Vec<crate::x::params::tweet_fields_parameter::TweetFields>>,
}

pub type Response = Get2DmEventsEventIdResponse;

