// AUTO-GENERATED by x-api-spec/codegen.py — do not edit by hand.
// Source: x-api-spec/openapi.json (sha256 dd4e81f817babcd5...)

//! HTTP call helpers for /2/dm_events/{event_id}.
#[allow(unused_imports)]
use crate::x::http::Http;
#[allow(unused_imports)]
use crate::x::Error;
#[allow(unused_imports)]
use reqwest::Method;

/// GET /2/dm_events/{event_id}
pub async fn get(
    http: &Http,
    req: &super::get::Request,
) -> Result<super::get::Response, Error> {
    let path = format!("dm_events/{}", urlencoding::encode(&req.event_id.to_string()));
    http.send_with_query(Method::GET, &path, req).await
}

/// DELETE /2/dm_events/{event_id}
pub async fn delete(
    http: &Http,
    req: &super::delete::Request,
) -> Result<super::delete::Response, Error> {
    let path = format!("dm_events/{}", urlencoding::encode(&req.event_id.to_string()));
    http.send::<_, ()>(Method::DELETE, &path, None).await
}

